### ISSUE TITLE
Migrate is creating text type instead of uuid type for @default(uuid()) in postgres

### ISSUE THREAD

**Issue by pantharshit00** [prisma/migrate#114]
Version: prisma2@2.0.0-alpha.159, binary version: bbbeff6f84b408e534ebd866bfd378748e6d6611

Right now lift is using the text type instead of the native uuid type for uuid id columns in postgres. 

Reproduction:

Just bootstrap the following model and observe the types created:
```groovy
model User {
  id   String @default(uuid()) @id
  age  Int?
  name String
}
```

**Comment by pantharshit00** [comment]
related: https://github.com/prisma/prisma2/issues/479

**Comment by divyenduz** [comment]
This is related to custom types: https://github.com/prisma/prisma2/issues/446

**Comment by albertoperdomo** [comment]
There is WIP to support uuid as a native type. See https://github.com/prisma/prisma/issues/3447
