### ISSUE TITLE
Move warning in lock file to the bottom

### ISSUE THREAD

**Issue by dimitarnestorov** [prisma/migrate#134]
At the moment entries in the lock file are ordered by date where the oldest are at the top the newest are at the bottom. The message though stays with the oldest migration at the top and after 15-20 migrations it will be missed in every diff viewing tool (your favorite Git client). Moving it to the bottom will yield more reads of it since it won't matter how many migrations are there, it will be visible in every diff.

As a positive side effect the "No newline at end of file" line won't be marked as added and removed on every change to the file.
![image](https://user-images.githubusercontent.com/8790386/64922667-75296400-d7da-11e9-9597-49adc38a59ff.png)
![image](https://user-images.githubusercontent.com/8790386/64922669-7bb7db80-d7da-11e9-9e0c-5414ba400a07.png)

Or maybe, even better, leave it at the top but place it at the bottom too.

**Comment by janpio** [comment]
Which message or warning?

**Comment by pantharshit00** [comment]
@janpio I think they mean the warning about the git conflict resolution:

```
# IF THERE'S A GIT CONFLICT IN THIS FILE, DON'T SOLVE IT MANUALLY!
# INSTEAD EXECUTE `prisma migrate fix`
# Prisma Migrate lockfile v1
# Read more about conflict resolution here: TODO

```

**Comment by dimitarnestorov** [comment]
Yes, this one

**Comment by Jolg42** [comment]
Closing as `migrate fix` command doesn't exists and this message was updated to reflect that.

For the ending new line this issue will track progress https://github.com/prisma/migrate/issues/157
