### ISSUE TITLE
Add linebreak at the end of `migrate.lock` file to avoid git history mess

### ISSUE THREAD

**Issue by schickling** [prisma/migrate#157]
![image](https://user-images.githubusercontent.com/1567498/66267051-f51c7a00-e82c-11e9-9b4e-b407ec9d7e84.png)

**Comment by Jolg42** [comment]
Dropping for now

**Comment by janpio** [comment]
Was this dropped or implemented?

**Comment by Jolg42** [comment]
Dropped :)

**Comment by janpio** [comment]
What about the git history mess? It is real and terrible if you are using the current migrate.

**Comment by Jolg42** [comment]
Well it's kind of a feature because it's the only way to know something happened.

You could merge successfully and a migration could sneak in without you noticing, right now there will be a conflict (really small and easy) and it helps understanding what's happening.
