### ISSUE TITLE
[Suggestion] Rename Migrate Commands

### ISSUE THREAD

**Issue by johannesschobel** [prisma/migrate#162]
Dear Prisma Team,

recently I came up with the suggestion to rename the Lift commands. In this context I propose the following changes:

```
prisma migrate save    --> prisma migrate commit
prisma migrate up      --> prisma migrate push
prisma migrate down    --> prisma migrate revert
```

This would make the commands more "git like" and (maybe) more memorable.

This would also reflect the fact, that a `save` is only a **local** change (same as with git commit) and in order to make this "commit" available, you need to `push` it to the database. 

The downside with this is, that - if you're a heavy git cli user - you may get confused with the similar commands :confused: 

Maybe it is also possible to have some kind of "aliases" for these commands? I am currently using custom `npm commands` in my `package.json` to alias those commands. For example, I'm using `db:commit` instead of `prisma2 lift save` and `db:push` for `prisma2 lift up`. Its shorter as well :smiley: 

What are your opinions on this?
All the best

**Comment by janpio** [comment]
(I moved this into `prisma/lift` as it concern functionality of that project)

Thanks for the suggestions here @johannesschobel, I am currently looking deep into what Lift does and why, and the names of the commands came up a few times during that already. But I also know there is quite a bit of history, so I will keep on gathering information and then report back.

**Comment by albertoperdomo** [comment]
Thanks. We are reviewing all the commands for migrate, currently.

**Comment by albertoperdomo** [comment]
ldata
