### ISSUE TITLE
[Question] Unique fields automatically defaulting to `''`

### ISSUE THREAD

**Issue by Jaspaul** [prisma/migrate#197]
I've been using lift locally to generate our migrations and noticed that marking a `field` as unique produces a field on the table that defaults to `''`. My expectation here would be that there is no default value. 

Is this behaviour expected?

```
model User {
  field    String      @unique
}
```

produces:

```
CREATE TABLE "User" (
  "field" text NOT NULL DEFAULT '',
}
```

expectation:

```
CREATE TABLE "User" (
  "field" text NOT NULL,
}
```

**Comment by mavilein** [comment]
See this [comment](https://github.com/prisma/prisma2/issues/741#issuecomment-546880979) for an explanation why this behavior exists. I think we are blocked by product input in this case.

**Comment by schickling** [comment]
@mavilein are you referring to this specs issue? https://github.com/prisma/specs/issues/277

**Comment by mavilein** [comment]
@schickling Yes. My comment did not refer only to enum fields but applies to every field type.

**Comment by tomhoule** [comment]
I think work on this bug is still blocked on the specs issue.

**Comment by timsuchanek** [comment]
We drop this for now, because the specs are missing.

**Comment by mavilein** [comment]
This is blocked by: https://github.com/prisma/specs/issues/308

**Comment by tomhoule** [comment]
The implicit defaults have been removed recently. Unexecutable migrations are currently reported as warnings. I think we can close this issue :)
