### ISSUE TITLE
Ability to combine --verbose and --preview for `migrate up`

### ISSUE THREAD

**Issue by sameoldmadness** [prisma/migrate#200]
I'd like to see which statements would be executed before actually executing them.

Will be useful to prevent data loss.

**Comment by pantharshit00** [comment]
Also, as a side note, now we prompt you to confirm the changes if data loss is involved

**Comment by pantharshit00** [comment]
This is still actionable in the latest version.

**Comment by albertoperdomo** [comment]
Thanks for taking the time to report this issue!

We've recently released a Prisma Migrate Preview ([2.1.3.0 release notes](https://github.com/prisma/prisma/releases/tag/2.13.0)), which has quite a few changes compared to the previous experimental version. 

In this version, you can use the --create-only option together with `prisma migrate dev`, to create a migration without applying it to the development database. The migration files are in plain SQL and the tool is deterministic, so it's 100% transparent in terms of statements. Before applying migrations to deployments like production or staging with `prisma migrate deploy`, you usually would have committed the migration files and it would be possible to review the statements before pulling the trigger.

We would encourage you to try out Prisma Migrate Preview. If you come across this or any other issue in the preview version, please feel free to open a [new issue in prisma/prisma](https://github.com/prisma/prisma/issues/new/choose).
For general feedback on Prisma Migrate Preview, feel free to chime in [on this issue](https://github.com/prisma/prisma/issues/4531).
