### ISSUE TITLE
[Bug] Error: Invalid migration step NaN

### ISSUE THREAD

**Issue by sameoldmadness** [prisma/migrate#203]
I've mistyped a command and got a cryptic error.

```
❯ npx prisma migrate up save
Error: Invalid migration step NaN
```

**Comment by sameoldmadness** [comment]
`"save" is not a valid migration step number` would be more helpful.

**Comment by pantharshit00** [comment]
This still exist in the latest version:
![image](https://user-images.githubusercontent.com/22195362/82868685-b1f15180-9f4a-11ea-9d51-b74cd37a15b7.png)

**Comment by albertoperdomo** [comment]
Please review @Jolg42

**Comment by Jolg42** [comment]
Thanks! 🙏
