### ISSUE TITLE
Migrations drop nullable -> non-nullable columns

### ISSUE THREAD

**Issue by br3nd4nn34l** [prisma/migrate#208]
I've noticed that if you have a data model with a nullable field:
```
model A {
  x String?
}
```

And you convert the field to non-nullable:
```
model A {
  x String
}
```

The migration ends up containing a command like:
```sql
ALTER TABLE "as"."x" DROP COLUMN "x",
ADD COLUMN "x" text NOT NULL DEFAULT ''
```

Unless I'm misinterpreting this instruction, the database would drop the `x` column and then replace it with a column full of empty strings. Is this intentional?

**Comment by Jaspaul** [comment]
@pantharshit00 How can I inspect the produced SQL you have above? Is there documentation you can point me to?

**Comment by pantharshit00** [comment]
@Jaspaul 

We have the exact SQL steps we perform in the README.md file which we generate with each migration in the migrations/ folder inside prisma/ folder.

**Comment by Jaspaul** [comment]
When we run this locally we only see:

```
ALTER TABLE "as"."x" DROP COLUMN "x",
ADD COLUMN "x" text NOT NULL DEFAULT ''
```

in the readme file.

We're running: `prisma2@2.0.0-preview013.3, binary version: 2b78c35cf302bf80ae5aaa863c5eee0d09541f83`

Could this be the reason why it's different?

**Comment by pantharshit00** [comment]
I am using the latest version which is `prisma2@2.0.0-preview016.1, binary version: 54c4d8ce690254b5d0c77a21361896a6ca3fc4b7`

Please upgrade and give this another shot

**Comment by tomhoule** [comment]
This is the expected behaviour currently (we will work on making more changes non-destructive at some point). You should get a warning and a confirmation dialog from lift when data loss would occur though. If you don't get a warning it's a bug we should fix.
