### ISSUE TITLE
_migration table not found on "prisma2 dev" - mysqldb

### ISSUE THREAD

**Issue by kumarwin** [prisma/migrate#218]
Prisma2 with localhost Mysql ( Windows 10 ) is not working. Throwing _migration table not found on "prisma2 dev"

**Comment by matthewmueller** [comment]
internal note: drop for a month

**Comment by divyenduz** [comment]
This is related to this spec issue: https://github.com/prisma/specs/issues/126

**Comment by divyenduz** [comment]
Internal note: dropping for now
