### ISSUE TITLE
`prisma migrate save` and `prisma migrate up` hang upon migration

### ISSUE THREAD

**Issue by nikolasburk** [prisma/migrate#220]
Reproduce:

1. Run `prisma2 init` and select GraphQL starter kit and TypeScript with local Postgres DB
1. Change `User` model to:

   ```
   model User {
     id        String @default(cuid()) @id
     email     String @unique
     firstName String
     lastName  String
     posts     Post[]
   }
   ```

1. Run `prisma2 lift save` 

Lift is hanging on this screen:

![image](https://user-images.githubusercontent.com/4058327/69615057-87bee580-1034-11ea-8f14-73d97c67a5f9.png)

After cancelling with ctrl+c, I run `prisma2 lift up` where the CLI hangs again:

![image](https://user-images.githubusercontent.com/4058327/69615176-c359af80-1034-11ea-87e8-bdf83cb2304b.png)

I need to cancel with ctrl+c again to get back control over my terminal.

**Comment by pantharshit00** [comment]
I am unable to reproduce this on a mac with `prisma2@2.0.0-preview017.1, binary version: 6159bf3a263921c3c28ee68e2c9e130b5a69c293`

Can you please check the processes and make sure only one instance of Prisma2 is running?
