### ISSUE TITLE
Huge migration dont pass

### ISSUE THREAD

**Issue by michaelchiche** [prisma/migrate#23]
I have a pretty big migration for the initial migration. and it fails saying
```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: QueryError(MySqlError { ERROR 1406 (22001): Data too long for column 'datamodel_steps' at row 1 }
```

I figured this meant that the value sent inside datamodel_steps is too long. so i checked what was supposed to be inserted. and the length of the string was 70k+ characters, which is longer than the max value for text of about 64k.

The easiest way to fix this would be to set this field type to `MEDIUMTEXT` for mysql

**Comment by mazzaker** [comment]
My schema is approximate 900 lines with spaces and comments.

**Comment by divyenduz** [comment]
What OS are you using? Does this issue still persist with the latest CLI version (preview 9.1)?

**Comment by mazzaker** [comment]
Windows + WSL with prisma2@2.0.0-preview-10, binary version: 1b0c271f14ca00606f56c93717e228fe48c5603c work for me without having this issue anymore.

**Comment by mazzaker** [comment]
On mac with the same version of prisma2 only empty _Migration table is created and no error message occurred.

**Comment by mazzaker** [comment]
If I change the fields datamodel_steps + datamodel_migration to MEDUIMTEXT, delete the migrations folder and rerun prisma2 lift save + prisma2 lift up the database on mac is correct.

mac mysql version: 5.7.25
WSL Debian: 10.1.38-MariaDB-0+deb9u1

**Comment by divyenduz** [comment]
@mazzaker Can you share your schema file please? In form of a minimal reproduction?
