### ISSUE TITLE
Updates in Prisma Schema datatype is not recognized by Lift

### ISSUE THREAD

**Issue by turbothinh** [prisma/migrate#232]
Change in Prisma Schema and generate Lift file from it does not update anything.
```
model User {
  id          String      @id @default(cuid()) @unique
  birthday    DateTime?  // Change to `String` and generate Lift file 
  firstName   String?
}
```

I ran `prisma2 lift save --name 'Init'` with the schema config above and `migrate` with **Lift** successfully. Then I tried changing the `birthday` type to `String` and run `prisma2 lift save --name 'user-change-brithday-data-type'`, Lift says `Everything up-to-date`.

**Comment by pantharshit00** [comment]
I am unable to reproduce this:
![image](https://user-images.githubusercontent.com/22195362/70251104-ef97cd80-17a4-11ea-97a6-2f4176d8a8bd.png)


Can you please share your migrations folder with me?

**Comment by turbothinh** [comment]
![image](https://user-images.githubusercontent.com/14198542/70542404-f5a4fa00-1b68-11ea-9871-0fa201a745d1.png)

@pantharshit00 Oh nice, I can generate migration now, but it was not working before, dunno what I did wrong. However, it says "There might be data loss when applying the migration". I think this is problematic because we can't afford losing data every single time we change/update schema. What is your opinion on this?

**Comment by pantharshit00** [comment]
You are trying to add a required field to a model which already has data. It is expected to get data loss as otherwise constraint would be violated.

So either, introduce it optionally and add data to the already existing columns for it or use the `@default` directive and add a default value for field in the existing rows.
