### ISSUE TITLE
Unable to add new required relational field to existing model

### ISSUE THREAD

**Issue by seanemmer** [prisma/migrate#240]
Database: PostgreSQL (Digital Ocean)

When I attempt to add a new relational field to an existing model with existing rows, I receive the following error:

```
thread 'tokio-runtime-worker-1' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
```

This behavior makes sense, but it is unclear what the migration path is for adding a new required relational field.  Prisma does not allow me to set a default for a relational field, and when I try to first set the relational field as optional and then make it required, I get an error (https://github.com/prisma/prisma2/issues/1063).

**Comment by janpio** [comment]
Thanks! 

It probably will not make a difference, but can you quickly conform that this is still the case with `latest`/`preview018.1`?

**Comment by seanemmer** [comment]
Still happening, error below:

`Error: Error in migration engine.
Reason: [src/libcore/option.rs:378:21] called `Option::unwrap()` on a `None` value`

**Comment by seanemmer** [comment]
@janpio Any updates on this?  This issue is 3 months old and preventing me from iterating on my datamodel.

**Comment by janpio** [comment]
No, work on `migrate` currently is pretty minimal as we focus on getting Prisma Client out the door.

Can you maybe create a new issue with some reproduction schema? Maybe we can prioritize it - but having a current schema with current error message and so on would help a lot.

**Comment by seanemmer** [comment]
@janpio ok, created a new issue with repro https://github.com/prisma/migrate/issues/379

**Comment by janpio** [comment]
Thank you - I think it is safe to close this one then. Let me know if the new issue is missing something from here.

Replaced by https://github.com/prisma/migrate/issues/379
