### ISSUE TITLE
 I set the default value to "utf8_general_ci" in mysql. but when I use prisma migrate up, the collation always changes to "latin1_swedish_ci"

### ISSUE THREAD

**Issue by loycord** [prisma/migrate#245]
<img width="401" alt="Screen Shot 2019-08-14 at 4 38 23 PM" src="https://user-images.githubusercontent.com/38197610/63003468-2cb51880-beb3-11e9-90e0-030c176cf19d.png">
<img width="223" alt="Screen Shot 2019-08-14 at 4 38 42 PM" src="https://user-images.githubusercontent.com/38197610/63003473-2e7edc00-beb3-11e9-94b5-cb8250b27704.png">

** version -
prisma2@2.0.0-preview-6, binary version: 4d17a0639165e5a8e54c7e5cf538ffdf114edb53

**Comment by tomhoule** [comment]
I tried to reproduce the issue with the latest migrate (`87846242af9393fb8fe9d3644cbb2dec2e322155`), and it appears to no longer be the case:

![Screenshot from 2020-07-07 14-33-52](https://user-images.githubusercontent.com/13155277/86782215-209fef80-c05f-11ea-8c0f-6a04e4a0286e.png)

![Screenshot from 2020-07-07 14-34-09](https://user-images.githubusercontent.com/13155277/86782213-20075900-c05f-11ea-8f49-e87b227b3b18.png)

Can you still reproduce the issue on your end?
