### ISSUE TITLE
At first datamodel change: Error in migrate engine for rpc applyMigration

### ISSUE THREAD

**Issue by Gbahaa** [prisma/migrate#25]
Reproduce
1- Prisma2 dev
2- Connect to MySql database 5.7 (in docker)
3- New Schema (any name) 
4- add simple model 

```
datasource db {
  provider = "mysql"
  url      = "mysql://root--[DELETED :) --]"
}

generator photon {
  provider = "photonjs"
}

model User {
  id    String  @default(cuid()) @id @unique
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean
  title     String
  content   String?
  author    User?
}
```

5- prisma2 dev -> success
6- change the model of User to be 
```
model User {
  id    String  @default(cuid()) @id @unique
  email String  @unique
  name  String?
  posts Post[]
  displayName String?
}
```

7- save -> error 

![Screenshot from 2019-06-27 16-43-18](https://user-images.githubusercontent.com/24666329/60247099-f8819a80-98fa-11e9-91a6-8be7f18c0f26.png)

Main Error: 
```thread 'main' panicked at 'The model User already exists in this data model. It is not possible to create it once more.'```

Ubunut 16.04
prisma2 0.0.97

**Comment by divyenduz** [comment]
@Gbahaa Thanks for reporting this one, did you introspect an existing database or create a new one? I am asking about steps before `prisma2 dev`.

**Comment by divyenduz** [comment]
I am able to reproduce this with a new schema as well as an introspected schema.

**Comment by divyenduz** [comment]
Another observation is that the migration actually goes through but migration engine fails to report that. A subsequent lift up leads to a "table already exists error".
