### ISSUE TITLE
 Error in migration engine.

### ISSUE THREAD

**Issue by garyro** [prisma/migrate#250]
The message asked me to post here the following is the entire message:

```
Error

Error: Error in migration engine.
Reason: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/io/driver/mod.rs:243:21] no current reactor

Please create an issue in the lift repo with
your `schema.prisma` and the prisma2 command you tried to use 🙏:
https://github.com/prisma/lift/issues/new

    at ChildProcess.child.on (/home/gary/Development/Server-V8-1/node_modules/prisma2/build/index.js:172365:35)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

More info:
I added a field to a model in my schema when I received the above.
Since I have updated to the latest preview version
prisma2@2.0.0-preview018.2, binary version: 3c4da1d6caa0c40a0210a346ec982c77f74e18c7
it has become impossible to add anything to any schema without getting all sorts of errors. 

I can delete the database on each change and all works fine. I have read a few other issues about migrations so I am at loss of what is going on but it all did start with updating the above version. My schema is fairly large about 300 lines.

If I can send any more info let me know.

**Comment by pantharshit00** [comment]
Hi,

Can you please tell me from which version you are upgrading? It is expected to receive some errors as there were breaking changes in between to improve further stability.

If you can't reproduce it on a fresh database, then it is fine. You just need to clear out your `_Migrations` table and delete existing migrations. No need to empty out the whole database.

**Comment by xlxAciDxlx** [comment]
I can reproduce this error on a completely fresh, unmodified install. Using Windows 10, TypeScript + REST API Starter Kit, and prisma2 preview 19.

**Comment by pantharshit00** [comment]
Can you try this on the latest version? We fixed a similar bug which removed the dependency that caused all of these issues so this might be already fixed.
