### ISSUE TITLE
Fields on the relationship connection

### ISSUE THREAD

**Issue by cdebotton** [prisma/migrate#253]
I haven't been able to find a related issue, so I apologize if this has been asked, or if this isn't the right place to ask this, but is it possible to add fields to a connection? For example:

```prisma
model Gallery {
  id String @id @default(cuid()) @unique
  title String
  images Image[]
}

model Image {
  id String @id @default(cuid()) @unique
  bucket String
  key String
  galleries Galery[]
}
```

I would like to be able to add an order field, or a layout field to the `Image` model within the context of the `Gallery` it is associated with, is there any way of handling that? Ideally it would add columns to the `_GalleryToMedia` table.

**Comment by mavilein** [comment]
This is in progress. The issue to track the actual work is this [one](https://github.com/prisma/prisma2/issues/816).
