### ISSUE TITLE
Error running two saved migrations

### ISSUE THREAD

**Issue by 2color** [prisma/migrate#257]
## What
Error running two saved migrations in a new project

## Version
`prisma2@2.0.0-preview018.2, binary version: 3c4da1d6caa0c40a0210a346ec982c77f74e18c7`

## Error output

https://gist.github.com/2color/e12242b2491a391fd2fcc7455b3087a2

## Workaround
Run `prisma2 lift up` after every `prisma save` 

## Steps to reproduce
1. `prisma init`
1. Choose Blank project
1. Choose Postgres
1. Set database details
1. Create postgres schema with CLI
1. Choose JavaScript
1. Choose just the Prisma schema

At this point the schema looks like this:
```
datasource db {
  provider = "postgresql"
  url      = "postgresql://postgres@localhost/woot?schema=woot"
}

generator photon {
  provider = "photonjs"
}

model User {
  id    String  @default(cuid()) @id @unique
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean
  title     String
  content   String?
  author    User?
}
```

1. Run `prisma2 lift save`
1. Add the `Comment` model to schema:
```
model Comment {
  id String @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  comment String
  author User?
}
```
1. Run `prisma2 lift up` - This step fails:

```
Response: {
  "jsonrpc": "2.0",
  "error": {
    "code": 4466,
    "message": "The migration engine panicked while handling the request. Check the data field for details.",
    "data": {
      "message": "Failure during a migration command: Generic error. (error: The model User already exists in this Datamodel. It is not possible to create it once more.)",
      "backtrace": null
    }
  },
  "id": 3
}
The migration engine panicked while handling the request. Check the data field for details.
```

**Comment by malekjaroslav** [comment]
Getting this as well

**Comment by pantharshit00** [comment]
Can you please try this again with the latest version? If you can still reproduce this, please reply here.
