### ISSUE TITLE
prisma2 dev failed-mysql

### ISSUE THREAD

**Issue by rakeshrana15** [prisma/migrate#266]
Migration failed  after running prisma2 dev command.

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: kill ESRCH
    at process.kill (internal/process/per_thread.js:189:13)
    at C:\Users\krakes\AppData\Roaming\npm\node_modules\prisma2\build\index.js:148922:21
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\krakes\AppData\Roaming\npm\node_modules\prisma2\build\index.js:148921:18)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\krakes\AppData\Roaming\npm\node_modules\prisma2\build\index.js:148907:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: kill ESRCH
```

```
Response: {
  "jsonrpc": "2.0",
  "error": {
    "code": 4466,
    "message": "The migration engine panicked while handling the request. Check the data field for details.",
    "data": {
      "message": "Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Error querying the database: Server error: `ERROR 42S02 (1146): Table 'testdb._migration' doesn't exist')",
      "backtrace": null
    }
  },
  "id": 3
}
The migration engine panicked while handling the request. Check the data field for details.

Wrote failed-applyMigration-20191221130710.md with debugging information.
Please put that file into a gist and post it in Slack.
```

![prisma2 failed migration](https://user-images.githubusercontent.com/20044916/71305272-39b0be00-23f7-11ea-94df-ef99fe224bbc.png)
![prisma2 migration error](https://user-images.githubusercontent.com/20044916/71305275-41706280-23f7-11ea-8c1a-5d5458ffdffe.png)

**Comment by rakeshrana15** [comment]
Error

Error: Error in migration engine.
Reason: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/io/driver/mod.rs:243:21] no current react
or

Please create an issue in the lift repo with
your `schema.prisma` and the prisma2 command you tried to use 🙏:
https://github.com/prisma/lift/issues/new

    at ChildProcess.<anonymous> (C:\Users\krakes\AppData\Roaming\npm\node_modules\prisma2\build\index.js:173452:35)
    at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:478:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

-------------Schema.prisma -------------------------------------------------------------------------------------------------------------
generator photon {
  provider = "photonjs"
}

datasource db {
  provider = "mysql"
  url      = "mysql://root:root@127.0.0.1/testdb"
}

model profile {
  AccountNo        Int?
  Active           String?
  Company          String?
  ContactNo        Int?
  DropPoint        String?
  DropTime         String?
  Email            String?
  EmergencyContact Int?
  Gender           String?
  HomeAddress      String?
  Name             String?
  OfficeAddress    String?
  PickupPoint      String?
  PickupTime       String?
  ProfileID        Int     @id
  ProfilePic       String?
  Rank             Int?
  User             String?
  VehicalOwner     String?
}

model users {
  Email        String?
  id           Int     @id
  Password     String?
  PasswordHash Int?
  RealName     String?
  RoleID       String?
  User         String?
}

**Comment by jfarcode** [comment]
I have the same problema and my schema.prisma is default project.

**Comment by pantharshit00** [comment]
Hi,

Sorry for the late reply here. Can you still reproduce this with the latest version? We have fixed a similar issue so this might be already fixed, so please try this again with the latest version.
