### ISSUE TITLE
Cockroachdb Support in Migrate

### ISSUE THREAD

**Issue by fire** [prisma/migrate#268]
Tracking interest and progress of Cockroachdb integration with migrate.

https://www.cockroachlabs.com/

**Comment by fire** [comment]
Appears to hang on connect.

**Comment by pantharshit00** [comment]
Can you please run lift in debug mode and paste the output here?

To enable debug mode, run `export DEBUG=*` before running your lift command.

**Comment by pantharshit00** [comment]
Also, we haven't tested lift with cockroachdb at all so rough edges are expected here. Under the hood, we use the rust driver for postgres: https://github.com/sfackler/rust-postgres#tokio-postgres-

**Comment by fire** [comment]
Sorry, I ran out of bandwidth to work on this.

**Comment by janpio** [comment]
Duplicate of https://github.com/prisma/migrate/issues/426

**Comment by albertoperdomo** [comment]
Global issue to track support for CockroachDB is [here](https://github.com/prisma/prisma/issues/2523).
