### ISSUE TITLE
Error: Error in migration engine.

### ISSUE THREAD

**Issue by Shoyadbek** [prisma/migrate#269]
Error: Error in migration engine.
Reason: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/io/driver/mod.rs:243:21] no curr
ent reactor

**Comment by pantharshit00** [comment]
Hi @Shoyadbek 

Can you please tell me how can I reproduce this? Also, please try your again with the latest version, this might be already fixed.
