### ISSUE TITLE
Error when running lift up

### ISSUE THREAD

**Issue by tvvignesh** [prisma/migrate#270]
Hi. I ran lift `prisma2 lift up` but I got this error saying about failed migration. I already have the migration in the db but was expecting prisma2 lift up to update it to the latest migration. I get the same error when running `prisma2 lift save` as well.

![Screenshot from 2019-12-27 18-18-24](https://user-images.githubusercontent.com/1165845/71517770-9ae40000-28d5-11ea-9d52-33480133b7b5.png)

I have added the logs to this gist: https://gist.github.com/tvvignesh/1efabb7e11f6c336a64510d26b0e3ae1

Am I doing something wrong?

**PS:** I deleted the migrations folder, dropped all tables in the db and then ran again afresh and it worked.

**Comment by pantharshit00** [comment]
@tvvignesh Can you still able to reproduce this? Can you list out the exact steps for reproduction here so that I can identify the bug?

**Comment by tvvignesh** [comment]
@pantharshit00 Looks like this was reported on 27th December (around a month ago). As of now, things are working fine after all the version upgrades and clean up of migrations from local and remote. if I face this again, will let you know. To be honest, since it has been a month, I don't even remember, how to reproduce this.

One thing though, while errors like these do indicate some sort of mismatch or problem in either the migrations or the database, I am not so sure sometimes on how to actually overcome such migration errors since most of them spit out either RUST specific errors or a huge json or RPC errors. In the future, it would be great to have error codes for migration errors with some sort of explanation on how to fix them. Thanks.

**Comment by pantharshit00** [comment]
I am closing this for now.

Over time as we gain more stability and document all error code, your other concern will get automatically addressed.
