### ISSUE TITLE
Migration process in 'prisma2 dev' deleted arrays in database

### ISSUE THREAD

**Issue by naveen-bharathi** [prisma/migrate#276]
## Migration process in 'prisma2 dev' deleted arrays in database

When I run the **`prisma2 dev`** command, the migration process deletes array field value and makes it **`NULL`** in the database

**Comment by pantharshit00** [comment]
@naveen-bharathi 

Sorry for the late reply here. Are you able to still reproduce this on the latest version? If yes, can you please provide me with your schema.
