### ISSUE TITLE
Ongoing issues with a column that has changed from required to optional

### ISSUE THREAD

**Issue by jwld** [prisma/migrate#279]
I'm finding that once I've changed a column from required to optional, any time I make any further changes to that schema, it's requiring me to wipe all the values from that original column, despite that migration supposedly having already taken place.

Relates to prisma/lift#278
Version is `prisma2@2.0.0-preview019`

**Steps to reproduce:**
1. Create a new project and fresh psql database
2. Create a new schema with the following:
```
model Post {
  id     String   @default(cuid()) @id
  name   String
}
```
3. Run `prisma2 dev`
4. Add a row to the `Post` table inside Prisma Studio
5. Update the schema to make name optional:
```
model Post {
  id     String   @default(cuid()) @id
  name   String?
}
```
6. Accept the warning and wipe the data in the `name` column
7. Go back into Prisma Studio and add some new data to the `name` column
8. Add a new column to the `Post` model:
```
model Post {
  id     String   @default(cuid()) @id
  name   String?
  test   Int
}
```

If I do the above (or make any other change in the schema) I see this message again:
```
⚠️   There will be data loss:

     • You are about to alter the column `name` on the `Post` table, which still contains 1 non-null values. The data in that column will be lost.
```

**Comment by malekjaroslav** [comment]
> Did you start fresh when trying this again? You migration folder might have obsolete steps.

@pantharshit00 I just asked about this above. Or is your question different?

**Comment by jwld** [comment]
Yes starting fresh every time

**Comment by pantharshit00** [comment]
>  I just asked about this above. Or is your question different?

Sorry I missed that 😅 


@jwld can you please try again with the latest version, we fixed many related issues in the past weeks so this might be already fixed now.

**Comment by jwld** [comment]
Ok this seems to be sorted now, can no longer replicate it. Thanks!
