### ISSUE TITLE
prisma dev error with existing mysql database

### ISSUE THREAD

**Issue by timonschenzel** [prisma/migrate#281]
I'm getting an error when running `prisma2 dev` when an existing database connected, I did report the error: report id 795.

**Steps**:
1. prisma2 init
2. Languages for starter kits: Blank project
3. Select the database you want to use: MySQL
4. Prisma Framework tools: Photon and Lift
5. Select the programming language you want to use: TypeScript
6. Start with a runnable demo script or just the Prisma schema: Demo script
7. cd prisma2
8. prisma2 dev

**Error**:
```
Error in migration engine: [2019-12-06T12:17:50Z INFO  quaint] Starting a mysql pool with 9 connections.
thread 'tokio-runtime-worker-0' panicked at 'Error parsing the migration steps: Error("unknown field `name`, expected `model`", line: 1, column: 76)', src/libcore/result.rs:1165:5
```
I could provide the mysql database schema, when needed.

**Comment by timonschenzel** [comment]
@divyenduz The original database was not migrated using Prisma 2. I'm trying to introspect this database with existing data within it.

**Comment by divyenduz** [comment]
@timonschenzel Can you try this again and share your findings?
