### ISSUE TITLE
[Preview 14] Migrate error - ambiguous self relation detected 

### ISSUE THREAD

**Issue by nhuesmann** [prisma/migrate#290]
Related to prisma/prisma2#488 and prisma/prisma2#671 

### Prisma2 version:
`prisma2@2.0.0-preview014, binary version: 188a379c9b8c6650e5812f9bdb7407d7b197692f`

### Schema:
```
model Game {
  id           String   @id @default(cuid())
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
  title        String
  handle       String
  description  String
  expansions   Game[]   @relation("Expansion")
  expands      Game[]   @relation("Expansion")
  relatedGames Game[]  👈 this is the problem
}
```

### Notes:
When I try to perform `prisma2 lift up` I get "ambiguous self relation detected" due to the `relatedGames` field. If I try to add the `@relation` directive, I get an error when I try to perform `prisma lift save` in which the schema can't be validated bc `Named relations require an opposite field`. In my model, the `expansions`/`expands` fields are different, because a Game can either have `expansions`, or it itself can be an expansion for several other games (meaning it will have several Games in its `expands` field). The `relatedGames` field doesn't have any concept of different roles in a relationship like `expansions` and `expands`, it's simply a way to model that games can be "related" to each other, i.e. for similar game recommendations. What should I do to resolve this?

**Comment by nhuesmann** [comment]
> @nhuesmann : Your concerns are right about this one. This still does not warrant the introduction of such a feature in my opinion since it occurs a performance cost for every relation.
> I understand that the solution of joining the arrays of both relation fields feels cumbersome. My advice in this case is to lift this relation into a proper model in your application. I would introduce a model called `Friendship` that contains two relation fields pointing to the befriended users. This would enable you write a query that gets you all friendships for a user. This would relieve you from joining those arrays manually.
> 
> **Example schema**
> 
> ```groovy
> model User {
>   id Int @id
>   friendships  Friendship[]
>   ...
> }
> 
> model Friendship {
>   id Int @id
>   user1 User
>   user2 User
> }
> ```
> 
> **Example Photon call:** (This is best effort code. Maybe this does not work exactly like that. Should convery the idea though)
> 
> ```ts
> const friendships: Friendship[] = await photon.friendships.findMany({
>   where: { 
>       OR: [
>           { user1: { id: 'abc' }},
>           { user2: { id: 'abc' }},
>       ]
>   },
> });
> ```

@mavilein I just ran into this issue while trying to implement a `Friendship` model. My model is very similar to the example you provided in the quoted comment above. My simplified schema:

```groovy
model User {
  id          Int          @id @default(autoincrement())
  friendships Friendship[]
  ...
}

enum FriendshipStatus {
  PENDING
  ACCEPTED
  DECLINED
  BLOCKED
}

model Friendship {
  id             Int              @id @default(autoincrement())
  status         FriendshipStatus @default(PENDING)
  user1          User
  user2          User
  lastActionUser User
}
```

Schema parsing fails with the following message:
> Error validating model "Friendship": Ambiguous relation detected. The fields `user1` and `user2` in model `Friendship` both refer to `User`. Please provide different relation names for them by adding `@relation(<name>).

It doesn't make sense to differentiate `user1` and `user2` with relation names since they both point to the same field (`friendships`) on the `User` model and contain references to 2 different `User` records. As discussed previously, this feels like a very common use case. I can get the model "working" by just storing strings in `user1`, `user2`, and `lastActionUser`, however if I wanted to retrieve a user's friends, I'd have to make a similar query to what you listed above to find the friendships, then I'd have to make a separate query for the user data for each friendship since only the plain string ids are stored.

I'd love to hear your/anyone else from Prisma team's thoughts, thanks!

**Comment by nhuesmann** [comment]
@divyenduz @mavilein I just wanted to follow up after a few weeks to see if this was going to be in any upcoming sprints. This is an important feature for me, as I need to model a friendship and currently can't (unless I figure out some undesirable workarounds, but they'd ultimately be subpar solutions).

**Comment by nhuesmann** [comment]
@divyenduz @mavilein Hi guys, just following up again after a few more weeks to see if there are any plans to fix this bug. I have a feature that depends heavily on this functionality. Thanks!

**Comment by mavilein** [comment]
@nhuesmann : There are no plans to change this behavior. My suggestion was more pseudo a spontaneous idea and i just realized that it won't work like that. The following schema should work:

```prisma
model User {
  id Int @id
  friendships1  Friendship[] @relation("Friendship1")
  friendships2  Friendship[] @relation("Friendship2")
}

model Friendship {
  id Int @id
  user1 User @relation("Friendship1")
  user2 User @relation("Friendship2")
}
```

This schema should enable the photon call i sketched in an earlier comment.

**Comment by nhuesmann** [comment]
@mavilein Thanks for the reply. I'll admit I'm a little bummed about having to set up these arbitrary back relation fields, but I understand there's a perf reason behind Prisma's decision to do this. I'll just hope that down the road there might be a slightly cleaner solve for this, but in the mean time I think this will take care of what I need. Thanks again.
