### ISSUE TITLE
Tutorial/Reference on managing migrations in production systems

### ISSUE THREAD

**Issue by tvvignesh** [prisma/migrate#292]
Hi there. I am using Lift and its awesome. But the problem is that, since its quite new, I am not having an idea on how to handle this when using Lift in production systems. Lot of questions crop up like:

1) Where do I store all the migrations? With source code? Separately or something else?

2) Should I keep a separate CI/CD pipeline for database migrations?

3) If I want to clean up migrations how do I do it?

4) Sometimes, the cli gets into interactive mode even with flags like -c and `--auto-approve` making the CI/CD pipeline fail. How do I avoid such things?

5) While lift takes care of data model/schema migrations? What happens to the data? How can I migrate that if say, my schema has changed over time? Does rolling back the schema rollback data as well to its previous state? If not, how will I do that?

6) If the error says that the local and remote migrations do not match, fine. But, how do I fix it apart from cleaning up the migrations table from the db and local folder which is what I have been doing so far.

Lot more questions like these when working with lift. It would be great to have a doc or tutorial on addressing real-world implementation of lift.

Thanks.

**Comment by Giorat** [comment]
Would love to see an explanation on this topic too to manage:

1. localhost database migration
2. pushed migrations to Git to the staging database to test out changes
3. finally pushed to the production database

**Comment by albertoperdomo** [comment]
Hello @tvvignesh @riccardogiorato,

Thanks for taking the time to report this issue!

We've recently released a Prisma Migrate Preview ([2.1.3.0 release notes](https://github.com/prisma/prisma/releases/tag/2.13.0)), which has quite a few changes compared to the previous experimental version. We've written documentation on the different flows, including development and production and they can be found here: https://www.prisma.io/docs/concepts/components/prisma-migrate/prisma-migrate-flows

We would encourage you to try out Prisma Migrate Preview. If you come across this or any other issue in the preview version, please feel free to open a [new issue in prisma/prisma](https://github.com/prisma/prisma/issues/new/choose).
For general feedback on Prisma Migrate Preview, feel free to chime in [on this issue](https://github.com/prisma/prisma/issues/4531).

If you think the new content is insufficient, please let us know!
