### ISSUE TITLE
Using Prisma enums results in setting DB-level default value

### ISSUE THREAD

**Issue by schickling** [prisma/migrate#293]
The following Prisma schema results in setting a default value for SQLite

![image](https://user-images.githubusercontent.com/1567498/66717822-9da67d00-eddd-11e9-9c3f-ae6dd598d92f.png)

![image](https://user-images.githubusercontent.com/1567498/66717825-a303c780-eddd-11e9-9c67-3dc44eb36736.png)

**Comment by tomhoule** [comment]
This is blocked on https://github.com/prisma/specs/issues/308

**Comment by janpio** [comment]
@tomhoule will post an update.

**Comment by tomhoule** [comment]
This is no longer the case, we do not rely on implicit defaults in the migration engine anymore. I think this issue can be closed :)
