### ISSUE TITLE
Migrate migration writes credentials out in the readme file

### ISSUE THREAD

**Issue by divyenduz** [prisma/migrate#310]
They should be masked.

**Comment by divyenduz** [comment]
Internal note: dropping from current sprint

**Comment by pantharshit00** [comment]
We do mask the credentials in the `schema.prisma` file stored inside of migrations folder:
![image](https://user-images.githubusercontent.com/22195362/83843888-94c73a80-a723-11ea-9a88-b5130cb368fe.png)

but we do not mask them in the diff we generated in the README if they are hard coded:
![image](https://user-images.githubusercontent.com/22195362/83843943-af99af00-a723-11ea-9699-53d1eca76db4.png)

**Comment by timsuchanek** [comment]
This is fixed in `2.1.1`.
