### ISSUE TITLE
Get an error with prisma2 migrate up --experimental - report id 1362

### ISSUE THREAD

**Issue by JCLMAQ** [prisma/migrate#319]
I try to push the schema.prisma to the postgres db.
The first command: prisma2 migrate -save "init" --experimental looks ok (if I run it withijn the prisma folder).
The secong command: prisma2 migrate up --experimental gives the error.
By the way, I get in the DB one table "_Migration", the other tables are not created.

**Comment by pantharshit00** [comment]
This has been fixed now in `2.0.0-preview020.2`. See: https://github.com/prisma/prisma2/issues/1419

I am going to close this, please comment here if you are still facing this.
