### ISSUE TITLE
EPIC: `prisma migrate` commands

### ISSUE THREAD

**Issue by schickling** [prisma/migrate#33]
- `prisma migrate up`: Run remaining migrations
- `prisma migrate down`: Rollback latest migration
- `prisma migrate status`: Print status information about migrations (#52)
- `prisma migrate drop`: Drop database(s)
- `prisma migrate reset`: `prisma migrate drop` + `prisma migrate up` + `prisma seed`
- `prisma migrate save`: Saves the latest schema changes as a new migration
- `prisma migrate squash`: Squashes together multiple migrations

## Later

- `prisma migrate redo`: Shortcut for `prisma migrate down 1 && prisma migrate up 1`

**Comment by matthewmueller** [comment]
Use cases for `prisma migrate reset` & `prisma migrate squash`: https://prisma.slack.com/archives/CKQTGR6T0/p1577591153177200
