### ISSUE TITLE
Migration fails with error: Invalid params: missing field `tag`.

### ISSUE THREAD

**Issue by phil-r** [prisma/migrate#338]
Error: 
```
Response: {
  "jsonrpc": "2.0",
  "error": {
    "code": -32602,
    "message": "Invalid params: missing field `tag`."
  },
  "id": 2
}
Invalid params: missing field `tag`.
```

Here is the file with debug info: https://gist.github.com/phil-r/18cc2e2c3e0c5c3da9fcc8ce3787d286

The strange thing is that the same migration runs fine locally(macOS), but fails on the server (in docker), although server has a much larger database.

**Comment by pantharshit00** [comment]
Hi @phil-r 

Sorry for the delay here. Can you please share your schema if possible? That way I can try to create a migration for a reproduction.

Also, please try again with the latest version once.

**Comment by phil-r** [comment]
Sorry for the delay here too ;)

Here is schema:

```
datasource db {
  provider = "postgresql"
  url      = "postgresql://postgres:REDACTED@db:5432/to_remember?schema=to_remember"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id           String   @default(cuid()) @id
  email        String   @unique
  name         String?
  devices      Device[]
  days         Day[]
  passwordHash String
  passwordSalt String
  lastLogin    DateTime @default(now())
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
}

model Device {
  id        String   @default(cuid()) @id
  name      String
  user      User
  token     String   @unique
  lastLogin DateTime @default(now())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model Day {
  id        String   @default(cuid()) @id
  title     String?
  user      User
  date      DateTime
  photoURL  String?
  photoInfo String?
  // Data type JSON may be introduced https://github.com/prisma/prisma2/issues/186

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
```

I will try with the latest version and come back with the result

**Comment by tomhoule** [comment]
This error message signals that the migrations are in an old format. If you delete the `prisma/migrations` folder and run `prisma2 migrate save` and `up` again it should work :)

**Comment by tomhoule** [comment]
We are expecting to continue making breaking changes to migrations until the release of `prisma2 migrate`, so this could break again until release, unfortunately.

**Comment by phil-r** [comment]
Sadly, I don't have time to test this for now, will return when migrate is in a more stable form.

**Comment by johhansantana** [comment]
deleting `migrations` folder and the `_Migration` table seems to do the trick in these situations. Hopefully this stables out on future versions. Currently on `2.0.0-beta.5`
