### ISSUE TITLE
prisma migrate squash

### ISSUE THREAD

**Issue by timsuchanek** [prisma/migrate#34]
TBD

**Comment by ctrlplusb** [comment]
Personally a fan of this idea, provides a few things:

- ability to do an occasional cleanup, lining up with major milestones on a project from which there is no going back.
- i run unit tests within which each test context bootstraps a db with the db migrations. minimising their workload is appealing.

An extension of this feature would be to allow squashing of a specific range of migrations, which may be handy in the case of feature branch development, allowing squashing a set of migrations into a single migration that represents the feature prior to merge.
