### ISSUE TITLE
Force yes on DB creation

### ISSUE THREAD

**Issue by webnoob** [prisma/migrate#347]
I've just upgraded to the latest preview021. My build pipeline boots up a test API, deletes the test SQLite DB and previously ran `prisma2 lift up`. At this point, it recreated my test database and things moved on from there.

I've now changed it to `prisma2 migrate up --experimental` but it's failing. When I run the command manually, it's prompting me to ask to create my `testing.db` database.

2 Questions:

1. Is there an option to force  a "Yes"
2. What has changed between the migrate / lift as this seems undocumented.

**Comment by pantharshit00** [comment]
> Is there an option to force a "Yes"
Yes, you can use the `--create-db` to automatically approve the change.

> What has changed between the migrate / lift as this seems undocumented.

You are likely hitting this bug: https://github.com/prisma/migrate/issues/316

**Comment by webnoob** [comment]
`--create-db` has solved my problem - thanks.
