### ISSUE TITLE
Wrong database creation on self relation list

### ISSUE THREAD

**Issue by cimchd** [prisma/migrate#356]
I use prisma2 version 0.21preview. My prisma schema looks like this:

```
model UserRole {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  name          String        @unique
  userRoles     UserRole[]    @relation(name: "IncludedUserRoles")
}
```

The resulting database table looks like this:
![image](https://user-images.githubusercontent.com/49520229/75021285-697e4f80-5494-11ea-9ef8-d24fa2289d84.png)

I expected that there is no field userRole but instead a relation table to handle multiple entries.
At the moment if I add multiple UserRoles, only the last entry will be persisted:
```
prisma.userRole.create({
      data: {
        name: 'superadmin',
        userRoles: {
          connect: [{ name: 'admin' }, { name: 'user' }]
        }
      }
    });
```

Am I doing something wrong? Is there a different way to define a schema that allows a UserRole to have many other UserRoles that it depends on?

**Comment by cimchd** [comment]
Thanks @pantharshit00 the table creation works now. But I think I did not use the right syntax to add some data.

When I run the `prisma.userRole.create` command from above I get the error message:
```
Invalid `prisma.userRole.create()` invocation in [...]

Reason: Error occurred during query execution:
InterpretationError("Error for binding \'1\': RecordNotFound(\"Expected 1 records to be connected, found 0.\")")

    at PrismaClientFetcher.request (/api/node_modules/@prisma/client/index.js:62:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by pantharshit00** [comment]
This error is thrown when the connect fields doesn't exist. Make sure they exist in the database.

**Comment by cimchd** [comment]
Thank you @pantharshit00 . It was my fault. I had an additional connect inside the prisma.create where the value did not exist.
