### ISSUE TITLE
Migration fails if existing table is in database

### ISSUE THREAD

**Issue by ryanking1809** [prisma/migrate#369]
I've been testing migration via `render.com` and their postgres database come with and existing table `spatial_ref_sys` the make my migrations fail. When I run `prisma2 migrate up --experimental`, I get the following error.

```
⚠️  There will be data loss:

  • You are about to drop the table `spatial_ref_sys`, which is not empty (5757 rows).

? Are you sure you want to apply this change? › (y/N)
```

If I don't apply the changes the migration isn't applied, and if I do, `render.com` prevents the table drop and the migration fails.

Is there a way to ignore this table during migration?

**Comment by janpio** [comment]
You could introspect the existing database first, and then add your new models to the existing schema. Then when you migrate, `migrate` should recognize the already existing table and just not do anything about it.

**Comment by ryanking1809** [comment]
Thanks, seemed to do the trick!
