### ISSUE TITLE
How to select datasource / database for migration

### ISSUE THREAD

**Issue by ryanking1809** [prisma/migrate#370]
if I have the following dev & production datasources in my `schema.prisma` file - is there a way to select either one individually for migration? 

```
datasource devdb {
  provider = "postgresql"
  url      = env("POSTGRES_URL_DEV")
}
datasource proddb {
  provider = "postgresql"
  url      = env("POSTGRES_URL_PROD")
}
```

**Comment by Jolg42** [comment]
Hello!

Just found out about this issue, for now Prisma will take the first one. So if you comment the first one it will take the next.

This is something that we want to improve in the future.

**Comment by ryanking1809** [comment]
All good, I ended up using `dotenv` in the end - but could be beneficial to have a solution out of the box.

```js
		"migrate-save-dev": "dotenv -e .env.development -- npx prisma migrate save --experimental",
		"migrate-up-dev": "dotenv -e .env.development -- npx prisma migrate up --experimental",
		"migrate-save-prod": "dotenv -e .env.production -- npx prisma migrate save --experimental",
		"migrate-up-prod": "dotenv -e .env.production -- npx prisma migrate up --experimental"
```

**Comment by Jolg42** [comment]
It looks like your feature request is related to https://github.com/prisma/prisma/issues/1255
