### ISSUE TITLE
prisma migrations: after.ts or after.sh spawn error on Windows

### ISSUE THREAD

**Issue by unlight** [prisma/migrate#372]
I'm trying to apply custom sql queries after migration. So I need create
`after.sh` or `after.ts`,
Example `after.ts`
```
#!/usr/bin/env node

console.log('ok');
```

When running migrate up, it erroing without details:
```
Error: spawn UNKNOWN
```

Same error with sh file with simple echo command.
Shell is `cmd.exe`, tried in `bash.exe` (built-in with git-for-windows) - same error.

OS: win 10 pro
node: v13.7.0
prisma: 2.0.0-alpha.902

**Comment by pantharshit00** [comment]
This seems to be a windows specific issue. I can confirm this.

**Comment by Jolg42** [comment]
Closing as `after.sh` & `after.ts` is not a supported feature as of today.

**Comment by unlight** [comment]
What is the replacement?

**Comment by Jolg42** [comment]
There is no replacement at the moment unfortunately, we're actively working on a better Prisma Migrate 😄 Nothing to try out yet.
