### ISSUE TITLE
Security issue with dependency - minimist

### ISSUE THREAD

**Issue by tvvignesh** [prisma/migrate#375]
Hi. When installing the latest version of migrate (tried both preview024 and the latest alpha release), I get security issues relating to prisma's dependency (or rather the studio-server) minimist (Screenshot below). You may want to consider updating the dependency. Thanks.

PS: This is affecting not just this package, but many other packages as well like kafka-node, eslint, etc. Some other issues similar to this here: 
https://github.com/eslint/eslint/issues/13050
https://github.com/wycats/handlebars.js/issues/1661

![Screenshot from 2020-03-19 23-32-09](https://user-images.githubusercontent.com/1165845/77099770-8594f280-6a3a-11ea-8530-01780cab5be6.png)

**Comment by Jolg42** [comment]
So the issue in the dependencies referenced in @prisma/sdk was coming from the package [@apexearth/copy](https://github.com/apexearth/copy/commits/master)

<img width="586" alt="Screen Shot 2020-04-22 at 12 57 50" src="https://user-images.githubusercontent.com/1328733/79974052-e760d600-8498-11ea-847c-ddf8750770b9.png">

It is now fixed 😄 

There is one more place were this low vulnerability can be found but it's in a devDependency https://github.com/bahmutov/snap-shot-it/issues/514 we'll wait for an update there but this should not be a security issue for you.

@madebysid will also update dependencies in Studio

**Comment by madebysid** [comment]
I've bumped up all dependencies in Studio as well now.

**Comment by Jolg42** [comment]
Ok so I will close this once the latest version of Studio is included then!

**Comment by Jolg42** [comment]
The latest version of studio is now in alpha so I will close this 😃 

It will be in the next beta.
