### ISSUE TITLE
Unable to migrate when a field is unique and is also defined under a composite index

### ISSUE THREAD

**Issue by pantharshit00** [prisma/migrate#376]
## Bug description
Right now when you try to migrate a model in which a field is marked as unique by the `@unique` directive and it is also defined under a composite index using `@@index` migrate throws a fatal exception instead of a warning or succeeding with the migration.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22195362/77309676-13b2f680-6d23-11ea-96e5-529fffb24026.png">

## How to reproduce
1. Use the following model:
```prisma
model User {
  id   Int    @id @default(autoincrement())
  name String @unique

 @@index([name])
}
```
2. Run `prisma2 migrate save --experimental`
3. Run `prisma2 migrate up --experimental`
4. See the error

## Expected behavior
Migrate should throw a warning if this is not possible or it should go ahead and succeed

## Environment & setup

- OS: MacOS 10.15.2
- Database: Postgres 11
- Prisma version: prisma2@2.0.0-preview024, binary version: 377df4fe30aa992f13f1ba152cf83d5770bdbc85
- Node.js version: 12.15.0

**Comment by pantharshit00** [comment]
This is still a problem in `alpha.1299`

**Comment by tomhoule** [comment]
I'll take this one.

**Comment by tomhoule** [comment]
I just reproduced this. This is a name collision between the index and the unique constraint. This should be fixed.
