### ISSUE TITLE
@@id([field1, field2]) is not working if the model have relations.

### ISSUE THREAD

**Issue by AmitGutpa** [prisma/migrate#381]
`@id([field1, field2])` does not work if the model have the relation. forexample:-
```prisma
model Mail {
    id Int   @default(autoincrement())
    createdAt  DateTime   @default(now())
    updatedAt  DateTime   @updatedAt
    body String
    to String
    from String
    subject String
    messageId String 
    date DateTime
    totalAttachments Int @default(0)
    totalSavedToS3 Int @default(0)
    totalErrors Int @default(0)
    attachments Attachment[]

    @@id([messageId, id])
}
```
This will give errors as this model has a relation. More likely the error has occurred because of the creation of two foreign keys in the attachment model. Otherwise, it works fine with the following mode 
```prisma
model Mail {
    id Int   @default(autoincrement())
    createdAt  DateTime   @default(now())
    updatedAt  DateTime   @updatedAt
    body String
    to String
    from String
    subject String
    messageId String 
    date DateTime
    totalAttachments Int @default(0)
    totalSavedToS3 Int @default(0)
    totalErrors Int @default(0)

    @@id([messageId, id])
} 
```

**Comment by pantharshit00** [comment]
Hi @AmitGutpa,

Sorry for the late reply here. Can you please try this again in the latest version and see if this works now. 

Also, if this is still failing, please share your whole datamodel. Like in the above example, I can't reproduce it without knowing what exactly you have in the attachment model.
