### ISSUE TITLE
preview025 causes migration error for Postgres db

### ISSUE THREAD

**Issue by heymartinadams** [prisma/migrate#383]
## Bug description
Unable to connect to postgres db with new `preview025`. Works with `preview024`.

## How to reproduce
1. Change schema.
2. Attempt to commit the changes: `npx prisma2 migrate save --experimental`

## Prisma information 
```
$ npx prisma2 migrate save --experimental
Error: Error in migration engine: Mar 27 08:44:36.142  INFO migration_engine: Starting migration engine RPC server git_hash="8814060fa684793b73d07dbfccd4b7777b3361ae"
Mar 27 08:44:36.659  INFO quaint::single: Starting a postgresql pool with 1 connections.
Mar 27 08:44:37.069  INFO tokio_postgres::connection: NOTICE: schema "public" already exists, skipping    
error Command failed with exit code 1.
```

## Environment & setup
- macOS
- PostgreSQL
- Prisma preview025
- Node.js version: 12.6.0

**Comment by janpio** [comment]
Is this reproducible with a new project created with `prisma2 init` and a trivial schema?

**Comment by heymartinadams** [comment]
Hi @janpio, was unable to reproduce my error, so closing...

**Comment by janpio** [comment]
We should look into this anyway for existing databaes.

**Comment by heymartinadams** [comment]
Lmk what you need from me to help you figure out what happened (no issues since, fyi).

**Comment by janpio** [comment]
Internal Note: This is about having a fallback error message when the engine dies and no real error message is returned.

**Comment by timsuchanek** [comment]
I had a quick look into this and provided invalid Postgres credentials, but can't reproduce this. Keeping this open until we have more info.

**Comment by heymartinadams** [comment]
It could very well have been due to my own not knowing what the heck I was doing, @timsuchanek — good chance that happened 😄

**Comment by janpio** [comment]
Closing for now then. Feel free to reopen or comment if something like this happens again.

**Comment by timsuchanek** [comment]
Seems like we forgot to close or GitHub didn't store it.
