### ISSUE TITLE
Try reducing child dependencies in migrate

### ISSUE THREAD

**Issue by tvvignesh** [prisma/migrate#387]
Hi. I did an analysis of the npm libs and dependencies in my project and migrate had the most number of dependencies. Screenshot below.

Are all the dependencies really needed? Just dropping a note here so that you can have a look when you get time since 849 is a huge number. Thanks.

![Screenshot from 2020-03-29 23-03-34](https://user-images.githubusercontent.com/1165845/77856114-8d128380-7212-11ea-8768-df92d1f49a11.png)

**Comment by janpio** [comment]
Some context:
https://npm.anvaka.com/#/view/2d/%2540prisma%252Fmigrate
http://npm.broofa.com/?q=@prisma/migrate

**Comment by Jolg42** [comment]
I did some cleanup a while ago so this is already fixed I think.
