### ISSUE TITLE
Missing env variable error message

### ISSUE THREAD

**Issue by rostaklein** [prisma/migrate#392]
## Problem
Small thing after upgrading to beta:
- When using the env variable as connection string and running e.g. `npx prisma migrate save --experimental` without the `DATABASE_URL` env variable provided, the error message I am getting is: `Error: Unknown database type dummy:` (this is actually the whole error message, no other context here)

I think this used to be a better error message back in the preview (something actually about the env variable missing).

## Solution
Display a correct error that this env variable is missing.

**Comment by jayanth1991** [comment]
Here is my folder structure:
```sh
proj/
    prisma/
        schema.prisma
    .env
    src/
```

It seems that if I don't put the `.env` file in the `prisma/` directory although i am running the `prisma migrate save --experimental` cmd from the root directory, its unable to recognize the environment vars.

I have to bypass this by including 2 .env files, unless there is a better way, I think this is not ideal.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
