### ISSUE TITLE
Prisma CLI cannot revert a migration

### ISSUE THREAD

**Issue by ranjan-purbey** [prisma/migrate#393]
## Bug description
When trying to revert a prisma migration using CLI, an error is thrown saying:
```
Error: Please provide the --experimental flag to use this command.
```

## Steps to reproduce the behavior:
1. Run `npx prisma migrate down 1 --experimental`
2. See error

## Expected behavior
Last migration should be reverted

## Prisma information
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model User {
  id Int @id @default(autoincrement())
  name String
}
```

## Environment & setup
- OS: Ubuntu 19.10
- Database: SQLite
- Prisma version: @prisma/cli: 2.0.0-beta.1
- Node.js version: v13.7.0

**Comment by ranjan-purbey** [comment]
However
```
npx prisma migrate down --experimental
```
as well as
```
npx prisma migrate down --experimental 1
```
works.

Moreover the `-p` or `--preview` flags are ignored when used with `migrate down` and result in actual rollback of a migration.

**Comment by Jolg42** [comment]
Thank you @ranjan-purbey for the issue.

I just fixed the flag issue here and opened a new issue for `prisma migrate down --preview --experimental` behavior https://github.com/prisma/migrate/issues/402

**Comment by Jolg42** [comment]
It will be available in alpha soon (dev build)
`npx @prisma/cli@alpha` and will be in beta.2 but I don't know when 🙃

**Comment by Jolg42** [comment]
Actually it will be in `npx @prisma/cli@2.0.0-alpha.1032` when it gets out of our currently broken pipeline 😄
