### ISSUE TITLE
migrate uses locale time for migrations filename instead of utc

### ISSUE THREAD

**Issue by dan-valentine** [prisma/migrate#396]
## Bug description

When migrations are run in a different timezone the order of the migrations can change if the first migration has a timestamp later than the second migration.

## How to reproduce

1. Generate a migration
2. Generate a migration from a timezone with an earlier time
3. Run migrations

## Expected behavior

Migrations stay in the same order locally and remotely

## Prisma information

Reproduceable on a new schema

## Environment & setup
running postgres in docker, and migrate through yarn

- OS: Widows 10
- Database: PostgreSQL
- Prisma version: 2.0.0-preview021
- Node.js version: v12.16.0

**Comment by Jolg42** [comment]
Fixed with https://github.com/prisma/prisma/pull/3175

Shipped in 2.4.0 🚀
