### ISSUE TITLE
Unable to add fields with @default(cuid())

### ISSUE THREAD

**Issue by seanemmer** [prisma/migrate#397]
## Bug description

Unable to add fields with @default(cuid())

## How to reproduce

Clone repo from prisma-examples/typescript/script

Add following to Post model:

`foobar:  String?  @default(cuid())`
or
`foobar:  String  @default(cuid())`

run ` prisma2 migrate save --experimental && prisma2 migrate up --experimental`

## Expected behavior

Migration succeeds and foobar field is a new CUID for each entry in the database

## Prisma information

Prisma Beta 1

## Environment & setup

Mac OSX

**Comment by pantharshit00** [comment]
I was able to optionally add the field and it is working correctly.

Adding is as required is causing the problem which is related to #236
