### ISSUE TITLE
`--preview` is ignored when doing `prisma migrate down --preview --experimental`

### ISSUE THREAD

**Issue by Jolg42** [prisma/migrate#402]
Thanks to https://github.com/prisma/migrate/issues/393#issuecomment-607116984 who found out :)

The flag is listed in the help output
<img width="604" alt="Screen Shot 2020-04-02 at 17 20 48" src="https://user-images.githubusercontent.com/1328733/78266690-67cd9000-7506-11ea-9503-b361f6b8cd39.png">

But it seems that this feature is not implement and should be done in
https://github.com/prisma/migrate/blob/59f77f08db960889f75a8c7a09120c8b377ec622/src/Lift.ts#L54-L56
https://github.com/prisma/migrate/blob/b09bf83bd68bddc96407824c25853ec1c9492894/src/cli/commands/LiftDown.ts#L76
https://github.com/prisma/migrate/blob/59f77f08db960889f75a8c7a09120c8b377ec622/src/Lift.ts#L440

**Comment by janpio** [comment]
Note: Remove it from help command and create issue to implement it in future.
