### ISSUE TITLE
Relation unrelated to migration throws error

### ISSUE THREAD

**Issue by BjoernRave** [prisma/migrate#404]
When trying to migrate my db up, I encounter the following error: 

```
Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Error querying the database: db error: ERROR: relation "Reserv
ation_movementId" already exists)
```

However my migration doesn't change neither reservation nor movement or movementId. 

The report Id is: `2638`

Prisma Version: 2.0.0-beta.1

Happy to provide more info

**Comment by pantharshit00** [comment]
@BjoernRave Are you still facing this? Unfortunately I was unable to reproduce this by looking into the error report. Can you please try this with `beta.2` once?

**Comment by BjoernRave** [comment]
@pantharshit00 I already deleted the db and set it up new, so sadly I can't try again. Will close it then I guess
