### ISSUE TITLE
Migration from preview024 to beta-1

### ISSUE THREAD

**Issue by tylerjbainbridge** [prisma/migrate#408]
## Bug description
I've tried everything to get `migrate` to work on my database from preview024 and have resorted to "starting over" via `prisma introspect` which breaks much of my existing client code

What was once:
```
user           User
```
becomes:
```
user          String
User          User            @relation(fields: [user], references: [id])
```

Which breaks all of the relationship-oriented code/queries from PrismaClient (since the User relation is now upper-case). This is just an isolated example, but this is happening for every instance of a relationship. 

I've tried to follow the "migration path" in the release notes, which seems to work for `prisma generate`, but threatens to clear hundreds of columns when the migration is actually run. 

Example:
```
⚠️  There will be data loss:

  • You are about to drop the column `user` on the `GoogleAccount` table, which still contains 23 non-null values.
```

I'm really hoping this can be resolved- I've been using Prisma 2 since the alpha started iin June 2019. I have an app built with a few dozen users, I don't want to risk losing their data or manually writing a bunch of complicated scripts just to be on the beta. Any help is _MUCH_ appreciated 🙏 

## How to reproduce
The bug should be reproducible by using preview024 with the "before" example above ^ -> migrating to the beta -> run any kind of migration.

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Prisma version: 2.0.0-beta.1
- Node.js version: v12.0.0

**Comment by janpio** [comment]
This might help, although not very elegant:

```
user          String
User          User            @relation(fields: [user], references: [id])

**Comment by tylerjbainbridge** [comment]
Hi @janpio - 

Using this schema:
```
userId        String		@map("user")
user          User          @relation(fields: [userId], references: [id])
```
Prisma migrate till warns it will clear `user`'s value (since the column has changed?)

**Comment by janpio** [comment]
Ok, that is unfortunate - then this workaround does not work for Migrate. Sorry.

**Comment by tylerjbainbridge** [comment]
For instance-

I get this message
```
• You are about to alter the column `user` on the `Collection` table, which still contains 8 non-null values. The data in that column will be lost.
```
Because of this SQL it generates
```sql
ALTER TABLE "public"."Collection" DROP CONSTRAINT IF EXiSTS "Collection_user_fkey",
ALTER COLUMN "name" DROP DEFAULT,
DROP COLUMN "user",
ADD COLUMN "user" text  NOT NULL ;
```

**Comment by tylerjbainbridge** [comment]
Do you know what the corresponding SQL would be to resolve this issue manually? (That I can repeat for each problematic foreign key)

**Comment by tomhoule** [comment]
It's hard to say without having the previous/next schemas (SQL and prisma) to compare, but it could possibly be because the `user` column used to be nullable, and it became required. Would it be possible to know the type of the `user` column in your current SQL schema? (with DBeaver or any database GUI for example)

**Comment by macrozone** [comment]
@ylerjbainbridge  i have now the same problem. Did you find a solution?

**Comment by macrozone** [comment]
if we would at least had something to rename fields, than this would be much easier. 

I have to ask: how did the prisma team update their own apps?

**Comment by tylerjbainbridge** [comment]
I had to jump through a ton of hoops- ended up writing a script using `knex` to update my existing data to the new format and manually updating the `schema.prisma` file. It was a total nightmare and took multiple days.

**Comment by tylerjbainbridge** [comment]
Here is a gist of the script I wrote- it's catered towards my own data so it may not be that helpful you, but I figured it may help you out a bit.

https://gist.github.com/tylerjbainbridge/7ec3dae9fc798f0984fdba85deb1676d

**Comment by macrozone** [comment]
> Here is a gist of the script I wrote- it's catered towards my own data so it may not be that helpful you, but I figured it may help you out a bit.
> 
> https://gist.github.com/tylerjbainbridge/7ec3dae9fc798f0984fdba85deb1676d
> 
> I basically renamed the columns from `user` to `userId` etc and changed the column type.

I like the fact that you named the file "save-me" ;-)

yeah, i ended up doing something similar:

1.) I manually adjust the schema to be compliant to prisma beta. I therefore had to add relation scalars, which i named <entity>Id. so a 

```
user     User
```

became

```
userId String
user    User @relation(fields: [userId])
```

2.) i then deleted all migrations in the folder and also in the database

3.) run this script which renames all existing relation scalars


```
import prisma from "../../prisma/prisma";

type Rename = String | { from: string; to: string };
type Table = string;

const renameFields = async (table: string, columns: Rename[]) => {
  const statements = columns.map((c) => {
    const { from, to } =
      typeof c === "string" || c instanceof String
        ? { from: c, to: c + "Id" }
        : c;
    return `
        ALTER TABLE "${table}"
        RENAME COLUMN "${from}" TO "${to}"
        `;
  });

  for (const statement of statements) {
    await prisma.raw(statement);
  }
  return;
};

type Migration = {
  table: Table;
  columns: Rename[];
};

const MIGRATIONS: Migration[] = [
  {
    table: "Challenge",
    columns: ["primaryTopic"],
  },
  {
    table: "Project",
    columns: ["challenge", "team", "thumbnail"],
  },
  {
    table: "Team",
    columns: ["challengeSelected", "primaryTopic"],
  },
  {
    table: "TeamChallengeVote",
    columns: ["team", "user", "challenge"],
  },
  {
    table: "User",
    columns: ["profilePhoto", "team"],
  },
  {
    table: "UserLoginToken",
    columns: ["user"],
  },
  {
    table: "UserResumeToken",
    columns: ["user"],
  },
];

const up = async () => {
  await prisma.raw`DROP TABLE _Migration`;
  for (const migration of MIGRATIONS) {
    try {
      console.log(await renameFields(migration.table, migration.columns));
    } catch (e) {
      console.error(e);
    }
  }
};

```

4.) i then ran `prisma migrate save --experimental` to create a fresh new migration and `prisma migrate up --experimental` to apply the migration. 

i tested this now locally and it worked, i hope i can do it on production. Won't be possible with our CI/CD setup though

**Comment by divyenduz** [comment]
@macrozone @tylerjbainbridge Thanks for the discussion on this issue. I see that the discussion has moved from the original topic and hence, I would close this issue. 

Please feel free to open a new issue with any specific improvements that you think are missed by closing this. 

Broadly, improving migrate is on our radar, including how it plays with introspection. 

Thanks 🙌
