### ISSUE TITLE
On failure _new tables/types are left

### ISSUE THREAD

**Issue by BjoernRave** [prisma/migrate#414]
Sometimes when I do a migration and it fails it leaves a `<Name>_new` table or type behind. 

This blocks all further migrations beacuse `<Name>_new already exists`. 

Is there a way to have a cleanup script, which always removes these tables/types?

**Comment by tomhoule** [comment]
We're aware of that for enums on postgres, have you encountered it with tables? (if so, on which database?)

My plan to fix this at the moment is to run these migrations inside a transaction so if it fails, everything is left as it was before.

**Comment by BjoernRave** [comment]
it was on postgres as well. But I don't quite remember the cirumstances anymore.

Sounds like a good plan
