### ISSUE TITLE
Add ability to define schema path for prisma migrate cli to help output

### ISSUE THREAD

**Issue by flybayer** [prisma/migrate#419]
## Problem

Prisma generate accepts a `--schema` argument for when your schema doesn't live in `prisma/`.

Prisma migrate also has this option, but does not document it in the `--help` output.

## Solution

Document `--schema` to prisma migrate, same as prisma generate.

**Comment by tvvignesh** [comment]
@flybayer Prisma migrate also accepts `--schema` in the args. For eg.

`npx prisma migrate up -c --auto-approve --schema="path/to/schema/schema.prisma" --experimental` does work.

One other feature which was filed by @janpio here: https://github.com/prisma/migrate/issues/361 is to use `--migrations` which is not yet supported.

**Comment by janpio** [comment]
Updated the issue to indicate that this is "only" missing in the `--help` output and thus hard/impossible to discover.

**Comment by Jolg42** [comment]
New output 💯 

<img width="588" alt="Screen Shot 2020-04-15 at 17 56 53" src="https://user-images.githubusercontent.com/1328733/79359264-ac175200-7f42-11ea-84d6-0039be514d67.png">
