### ISSUE TITLE
Self relation one-to-many can not insert data

### ISSUE THREAD

**Issue by lglie** [prisma/migrate#422]
```prisma
model User {
  id       Int     @id
  name     String?
  parent   User?   @relation("parentChildren", fields: [parentId], references: [id])
  parentId String?
  children User[]  @relation("parentChildren")
}
```

When inserting the second data to the same parent node, the following error message appears:
```
Unique constraint failed on the fields: (`parentId`)
    at PrismaClientFetcher.request {
  code: 'P2002',
  meta: { target: [ 'parentId' ] }
}
```

**Comment by squirly** [comment]
I was previously having this issue with `2.0.0-beta.1` and reordering fixed it.

I just upgraded to `2.0.0-beta.2`, reverted the reordering, and everything is working as it should. I would say that this bug has been **fixed**!

**Comment by pantharshit00** [comment]
I am waiting for @Iglie to respond before closing the issue

**Comment by lglie** [comment]
In later versions, this has not happened




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Harshit Pant"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 晚上8:02
收件人:&nbsp;"prisma/migrate"<migrate@noreply.github.com&gt;;
抄送:&nbsp;"廖国烈"<532875676@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [prisma/migrate] Self relation one-to-many can not insert data (#422)





 
I am waiting for @Iglie to respond before closing the issue

**Comment by pantharshit00** [comment]
Awesome, so I am going to close this now
