### ISSUE TITLE
Validation for primary fields being optional

### ISSUE THREAD

**Issue by tvvignesh** [prisma/migrate#423]
Hi. I had a bug in my schema where a field declared as a primary key was given as optional. Still, VSCode did not report any error and even migration happened properly. The error came up only when applying the migration.

Considering a model like this:

```prisma
model Test {
  userID  String
  privacy Privacy? @relation(fields: [Privacy], references: [id])
  Privacy String?

  @@id([userID, Privacy])
}

model Privacy {
  id         String     @default(cuid()) @id
  visibility String
}
```

The field `privacy` cannot be optional since it is declared as a part of the composite key. But this does not report error during migration as well as in VSCode.

When applying the migration:

`Error querying the database: Error querying the database: db error: ERROR: column "Privacy" is in a primary key`

![Screenshot from 2020-04-15 20-27-03](https://user-images.githubusercontent.com/1165845/79352446-7fba0080-7f57-11ea-85e2-6aec7bda1e6c.png)

**Comment by pantharshit00** [comment]
Thanks for reporting this. I can actually apply this schema with `beta.3` but the schema and database schema are inconsistant so we need to validate this case properly.

**Comment by albertoperdomo** [comment]
Will attempt to repro in 2.5.0
