### ISSUE TITLE
Changing field from non unique to unique throw an error instead of data loss warning

### ISSUE THREAD

**Issue by greben99** [prisma/migrate#441]
Report id 5126

Unknown error, no details on what the problem is. 

Let me know if you need the schema. Also, is there a way to view the error report.

Cheers

Version 2.0.0-beta.4

**Comment by pantharshit00** [comment]
![image](https://user-images.githubusercontent.com/22195362/83861921-d87b6d80-a73e-11ea-89e9-a79f2309bf9e.png)


I can confirm the bug, we should be throwing a data loss warning instead.

**Comment by tomhoule** [comment]
We do have a warning for this now. Closing this issue, thanks for reporting!
