### ISSUE TITLE
Issue in Migrate save after DB Introspection.

### ISSUE THREAD

**Issue by tarazena** [prisma/migrate#444]
Hi
I'm trying to update Prisma to the latest beta version, I decided to do an introspection for my current DB and create a new migration, however its producing an error (I can't see what the error details is)

report id 5174.

**Comment by pantharshit00** [comment]
Hi @tarazena,

Can you please share a SQL dump of your database so that we can reproduce this issue? Right now the error report doesn't contain sufficient information for a reproduction.

Also, sorry for bit of a late response here.

**Comment by tomhoule** [comment]
The versions involved here are so far from the current ones, it would be better to create a new issue if you experience a problem with the same database again.
