### ISSUE TITLE
Output an error instead of defaulting to the mysql database

### ISSUE THREAD

**Issue by steebchen** [prisma/migrate#445]
## Bug description

When not specifying a database in a MySQL connection string, the database defaults to `mysql`, but instead should output an error that you should probably not use this database.

## How to reproduce

```
docker run --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=pw -d mysql:5.6
yarn prisma migrate save --create-db --name "init" --experimental
yarn prisma migrate up --experimental
```

## Expected behavior

Should not default to `mysql`. Probably should fail instead.

## Prisma information

```prisma
datasource db {
	provider = "mysql"
	url      = "mysql://root:pw@localhost:3306"
}

generator db {
	provider = "prisma-client-js"
}

model User {
	id       String  @id @default(cuid())
	email    String  @unique
	username String
	name     String?
}
```

## Environment & setup

- OS: [e.g. Mac OS, Windows, Debian, CentOS, ...] macOS Catalina
- Database: [PostgreSQL, MySQL, MariaDB or SQLite] MySQL
- Prisma version: [Run `prisma -v` to see your Prisma version] 2.0.0-beta.5
- Node.js version: [Run `node -v` to see your Node.js version] v10.16.3

**Comment by tomhoule** [comment]
This is already implemented, I think this issue can be closed.
