### ISSUE TITLE
Relation fields are being wiped when running "migrate save" for the first time

### ISSUE THREAD

**Issue by jwld** [prisma/migrate#450]
## Bug description

Relation fields in prisma 1 are nullable. When running "migrate save" for the first time with our new prisma 2 schema it seems to be making them not nullable, but is wiping the existing data in the process. Relates to an [old issue](https://github.com/prisma/migrate/issues/278#issuecomment-581385333) I made but thought I'd make a new one since so much has changed since then.

**Logged warnings**
```
• You are about to alter the column `coordinates` on the `Address` table, which still contains 3 non-null values. The data in that column will be lost.
• Made the column `coordinates` on table `Address` required, but there are existing NULL values.
```

## How to reproduce

- Create prisma 1 table `Address` with required relation `coordinates` pointing to `Coordinates` table
- Add some data to the tables
- Create prisma 2 schema
- Run `npx prisma migrate save --experimental`

## Prisma information

**Prisma1 Schema**
```
type Address {
  coordinates: Coordinates! @relation(onDelete: CASCADE)
  id: ID! @id @unique
}

type Coordinates {
  id: ID! @id @unique
}
```

**Prisma2 Schema**
```
model Address {
  coordinates   Coordinates @relation(fields: [coordinatesId], references: [id])
  coordinatesId String      @map("coordinates")
  id            String      @default(cuid()) @id
}

model Coordinates {
  address   Address
  id        String   @default(cuid()) @id
}
```

## Expected behavior

The fields shouldn't be wiped when they have existing values.

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Prisma version: 2.0.0-beta.5
- Node.js version: 13.13.0

**Comment by tomhoule** [comment]
These migrations are not longer lossy, so I think we can close this issue. Thanks for reporting!
