### ISSUE TITLE
Migration should use the latest environment variable

### ISSUE THREAD

**Issue by Sytten** [prisma/migrate#451]
## Problem
If you change the environment variable in the newest prisma, you still need to keep the old environment variable alive or change it inside the steps for each migration. 

## Suggested solution
- The migration should use the latest environment variable.
- The migration provides an automated way to upgrade the migrations (similar to the use case of API breaking change in the engine that requires a change of all migrations)

## Alternatives
The user changes every migration manually.

**Comment by pantharshit00** [comment]
I will consider this more of a bug. @tomhoule what are your thoughts?

**Comment by albertoperdomo** [comment]
Please review @tomhoule

**Comment by tomhoule** [comment]
I just tried to reproduce https://github.com/prisma/migrate/issues/296 this morning, and I can confirm that now, datasource `url` fields are always anonymized to `***` in steps.json. This should no longer be a problem, I think we can close this issue.
