### ISSUE TITLE
5387 - Can't make migrations

### ISSUE THREAD

**Issue by TheDormouse** [prisma/migrate#452]
It took me a little bit to figure out what I was doing wrong, but I was pointing to a database from a different project. The error messaging is different from beta.4, so it lead to a bit of confusion.

Error in 2.0.0-beta.5

> Error in migration engine.
> Reason: [migration-engine/connectors/sql-migration-connector/src/lib.rs:240:9] Deserializing the 
> database migration failed.: Error("missing field `dataType`", line: 0, column: 0)

Error given in 2.0.0-beta.4 

> Error: There are more migrations in the database than locally. This must not happen. Local migration ids: . Remote migration ids: 20200505195906-init, 20200505200209-removeuser, 20200505200520-makeunique, 20200505202754-makeuniquetext, 20200505203343-removeuniquetext

**Comment by pantharshit00** [comment]
Looks like the migration are out of sync. Migrate is in experimental phase so this might happen sometimes.

In order to fix it you will need to reset your migrations. Delete the `_Migrations` table in your database and also delete `prisma/migrations` folder and try again with the latest version

**Comment by pantharshit00** [comment]
Docs: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-migrate#troubleshooting

**Comment by joneslloyd** [comment]
@pantharshit00 This worked for me, thanks!

**Comment by RoMay** [comment]
thanks, it works. Just a minor notice: you should delete the `_Migration` table, not `_Migrations`

**Comment by pantharshit00** [comment]
@RoMay Oh yeah, typo from my side. Updated the comment
