### ISSUE TITLE
Minor spelling error

### ISSUE THREAD

**Issue by heymartinadams** [prisma/migrate#454]
![image](https://user-images.githubusercontent.com/11673745/81960244-80c96680-95c5-11ea-94dc-153f5968538a.png)

☝️ See ...database **ev**.db

`beta.5`

**Comment by pantharshit00** [comment]
Hey @heymartinadams 

This is a actually a bug which was reported here: https://github.com/prisma/migrate/issues/283

So closing as a duplicate
