### ISSUE TITLE
migrate doesn't drop autoincrement on an id field

### ISSUE THREAD

**Issue by divyenduz** [prisma/migrate#467]
## Bug description

When the schema is changed to drop `auto_increment` on a Int ID field, the migration is a success but the `auto_increment` is not dropped in the database

## How to reproduce

1. Migrate the following schema

```
model User {
    id   Int @default(autoincrement()) @id
    name String
}
```

2. Drop the `autoincrement` and migrate the schema again

```
model User {
    id   Int @id
    name String
}
```

3. Observe that the DB still as auto_increment on the ID field. 

## Expected behavior

The `auto_increment` should be dropped from the database OR the migrate CLI should warn the user that this operation did not succeed. 

## Prisma information

```
@prisma/cli          : 2.0.0-beta.8
```

## Environment & setup

- Database: `MySQL`

**Comment by tomhoule** [comment]
The problem is pretty complicated, I just created another issue that relates this to schema-level problems: https://github.com/prisma/migrate/issues/467
