### ISSUE TITLE
Changing IDs in explicit n-m relationship results in no change

### ISSUE THREAD

**Issue by zigzactly** [prisma/migrate#468]
## Bug description

Changing IDs in an explicit n-m relationship is run successfully in migrate up, but does not have any effect in the database.

## How to reproduce

I have an explicit n-m relation defined. 

Before Schema:

```
model Person {
  id String @default(cuid()) @id
  Employee Employee[]
}
model Company {
  id String @default(cuid()) @id
  Employees Employee[]
}
model Employee {
  id String @default(cuid())
  person Person @relation(fields: [personId], references: [id])
  personId String
  company Company @relation(fields: [companyId], references: [id])
  companyId String
}
```
I made a change to the Employee table to include the Employee Id as part of the pkey. Removed personId for various reasons.
After Schema:

```
model Person {
  id String @default(cuid()) @id
  Employee Employee[]
}
model Company {
  id String @default(cuid()) @id
  Employees Employee[]
}
model Employee {
  id String @default(cuid())
  person Person @relation(fields: [personId], references: [id])
  personId String
  company Company @relation(fields: [companyId], references: [id])
  companyId String

  @@id([id, companyId])
}
```
Migrate Save and Migrate Up shows a successful migrate. But upon closer inspection, the migration README.md shows that there were no Database Steps defined:
```
```sql

```

## Expected behavior

If my understanding is correct, if there is a change to the ID defined in the prisma schema:
1. a drop of the existing index should happen
2. add a new key to reflect change
```
ALTER TABLE "public"."Employee" DROP CONSTRAINT "Employee_pkey";

ALTER TABLE "public"."Employee" ADD PRIMARY KEY ("companyId", "id");
```

But nothing is happening on the database level.

Since the actual migration did not change the primary key, i did a manual drop and add index on my own and reflected that in the Database steps and saved the README. I dont know enough about migrate to know if i should or should not do that.

Advice please!

## Prisma information

"@prisma/cli": "^2.0.0-beta.5"
PostgreSQL

**Comment by tomhoule** [comment]
Right now the workaround is to do the migration in SQL directly. We haven't had much time to work on this yet, but primary key migrations are a tricky if you want to do them without data loss, because in the presence of foreign keys, you either have to drop all the data in the table and the tables that reference it, or go through an elaborate process involving data migrations.

I'm sure we'll come up with a solution to this in time, but at the moment `migrate` doesn't deal with primary key migrations very well.

**Comment by janpio** [comment]
Internal Note: We will try to show a helpful error message here that links to this issue.

**Comment by zigzactly** [comment]
Nice. Looking forward to the solution!

**Comment by tomhoule** [comment]
I confused this with another issue, hence the re-scheduling, but this should be working, as of 2.2.0. Can you confirm this on your end?
