### ISSUE TITLE
When importing @prisma/migrate v8 error

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/migrate#469]
## Bug description

When

```ts
import { MigrateEngine } from '@prisma/migrate'
```

Then logged in terminal:

```
(node:11423) V8: /Users/jasonkuhrt/projects/graphql-nexus/nexus-schema-plugin-prisma/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:1781 Linking failure in asm.js: Unexpected stdlib member
```

## How to reproduce

```ts
import { MigrateEngine } from '@prisma/migrate'
```

## Expected behavior

No log

## Prisma information

N/A

## Environment & setup

- OS: Mac OS
- Database: N/A
- Prisma version: `2.0.0` 
- Node.js version: 12.x

**Comment by Jolg42** [comment]
So this is caused by `ink` and we actually do not use it anymore, so removing the code using it will get rid of that 🎊

**Comment by albertoperdomo** [comment]
Is this blocking you @jasonkuhrt ?

**Comment by jasonkuhrt** [comment]
@albertoperdomo no and I'm not sure it is still happening.

**Comment by Jolg42** [comment]
Ink was completely removed in https://github.com/prisma/prisma/pull/3854
