### ISSUE TITLE
Abort on unexecutable migrations

### ISSUE THREAD

**Issue by tomhoule** [prisma/migrate#471]
## Problem

Unexecutable migration messages from the migration engine are displayed as warnings, that the user can ignore. But they do mean that if you try to run the migration, it won't work, so we would need to prevent migrations from being applied in that case.

## Suggested solution

Display these messages separately from migrations and remove the option to apply the migration anyway.

## Alternatives

None that I know of.

## Additional context

We discussed this in the migrations team internally.

**Comment by Jolg42** [comment]
Current behavior 
<img width="812" alt="Screen Shot 2020-07-07 at 16 10 51" src="https://user-images.githubusercontent.com/1328733/86795524-f1dd4580-c06d-11ea-9df0-803d09d61c3a.png">
