### ISSUE TITLE
Suggest using `name` on index when creation fails because of length

### ISSUE THREAD

**Issue by janpio** [prisma/migrate#472]
https://github.com/prisma/docs/issues/434 has the details about the problem. This could possibly be nicely handled by migrate.

**Comment by tomhoule** [comment]
I think we do this right, now. Candidating this issue to confirm that we do not crash anymore.

**Comment by do4gr** [comment]
First task is to try to reproduce whether we still error.

**Comment by do4gr** [comment]
We do not crash anymore in this case but instead automatically truncate the internal autogenerated name. If the user provides a name in the schema, that one is used instead. So nothing to do here.
