### ISSUE TITLE
Replace interactive ink / react terminal with `prompts`

### ISSUE THREAD

**Issue by Jolg42** [prisma/migrate#473]
https://github.com/search?q=ink+repo%3Aprisma%2Fprisma+path%3Asrc%2Fpackages%2Fmigrate&type=Code&ref=advsearch&l=&l=

**Comment by albertoperdomo** [comment]
Internal note: deferred

**Comment by Jolg42** [comment]
I removed ink from one part of the CLI and replaced by prompts, we'll keep the other ink parts for now.
