### ISSUE TITLE
And It looks like the highlighting is doing something weird on the comments

### ISSUE THREAD

**Issue by janpio** [prisma/migrate#475]
And It looks like the highlighting is doing something weird on the comments 
<img width="513" alt="Screen Shot 2020-04-24 at 16 27 56" src="https://user-images.githubusercontent.com/1328733/80223433-9263c200-8648-11ea-9c2a-13f182571e97.png">

_Originally posted by @Jolg42 in https://github.com/prisma/prisma/issues/2295#issuecomment-619044444_

**Comment by tomhoule** [comment]
Not relevant anymore in preview migrate. Thanks!
