### ISSUE TITLE
Cannot migrate name or type updating required fields

### ISSUE THREAD

**Issue by WellFail** [prisma/migrate#476]
For example, I have some schema like this:
```
model User {  
  email       String          @unique  
  id          String          @id @default(cuid())  
  role        Role              
}
enum Role {
  ADMIN
  AUTHOR
}
```

I need to rename my enum to UserRole for example.
It is not a problem, but if I have a user in the database with a role I get an error `Null constraint failed: (role)`

This error was produced because the migration engine cannot handle name updating of enum
Migration engine trying to remove enum and create new with the new name

```
{
  "version": "0.3.14-fixed",
  "steps": [
    {
      "tag": "CreateEnum",
      "enum": "UserRole",
      "values": [
        "ADMIN",
        "AUTHOR"
      ]
    },
    { 
      "tag": "DeleteEnum",
      "enum": "Role"
    },
    {
      "tag": "UpdateField",
      "model": "User",
      "field": "role",
      "type": "UserRole"
    }
  ]
}

```
sql:

``` 
CREATE TYPE "UserRole" AS ENUM ('ADMIN', 'AUTHOR');

ALTER TABLE "test2373"."User" DROP COLUMN "role",
ADD COLUMN "role" "UserRole" NOT NULL ;

DROP TYPE "Role"
```

Same error can be produced when you try to change type or name of required fields, or making  optional field required when in the database stored null value on this field.

In the old versions of migrate for example `"@prisma/lift": "^0.3.384"` this problem does not produced though have equal steps after migrate.

In the older versions of migrate that work because thats set the default value.

```
ADD COLUMN "role" "UserRole" NOT NULL DEFAULT 'ADMIN';
```

I think that we need a way to solve such problems automatically.

For example with enum rename case we can use `ALTER TYPE "Role" RENAME TO UserRole`

**Comment by tomhoule** [comment]
This is not an issue anymore in contemporary versions of prisma.
