### ISSUE TITLE
Adding default value after initial migration

### ISSUE THREAD

**Issue by florianmartens** [prisma/migrate#479]
I am unable to create default values for existing columns using `npx migrate save --experimental`

**Steps to reproduction:**

**Run migration for:** 
```
model Organization {
  uuid              String @id @default(uuid())
  creationDateTime  String
}

```

**Change model to this and run migration:**

```
model Organization {
  uuid              String @id @default(uuid())
  creationDateTime  String @default(now())
}
```

**Error:**
> Error in migration engine.
> Reason: [migration-engine/connectors/sql-migration-connector/src/sql_renderer/postgres_renderer.rs:60:39] internal error: entered unreachable code: NOW default on n
> on-datetime column

> Please create an issue in the migrate repo with
> your `schema.prisma` and the prisma command you tried to use 🙏:
> https://github.com/prisma/migrate/issues/new

**Comment by florianmartens** [comment]
Sorry, I opened this prematurely:
The creationDateTime column had the wrong type. It needs to be: 
`creationDateTime  DateTime @default(now())`

The error message is actually quite descriptive so, my bad!

**Comment by pantharshit00** [comment]
I opened https://github.com/prisma/migrate/issues/482 to track this.
