### ISSUE TITLE
Initial migration for existing databases after introspect

### ISSUE THREAD

**Issue by ianwensink** [prisma/migrate#481]
## Problem
When using the awesome introspect feature, I run into an issue with the initial migration. For me, introspect is a way to setup a new Prisma project with an existing production database.

After introspect and generating the initial migration, running the migration in production won't work. Since this migration assumes an empty database, it will result in drop statements and thus data loss warnings.

## Suggested solution
Would be great if there is a to integrate a new Prisma project into an existing database, for instance by skipping the first migration. Generally, the initial migration will 100% match the production database you introspected from, so running it seems redundant. If the CLI would detect that in any way, that would smoothen the introspection process greatly.

## Alternatives
I currently would go about resolving this by manually copying the `_Migration` record from my local database after running the initial migration. Running the record as an insert in production, will fool the database into thinking it already ran the initial migration.

This is very error prone. Generating a valid "get-your-production-database-up-and-running"-query/migration after introspect could be a way to solve this.

**Comment by mavilein** [comment]
@ianwensink : Did you actually test this behavior? During `migrate up` we don't assume an empty database. Once `migrate up` is run we actually check the underlying database and see that the right tables are already there and won't do something.

cc @tomhoule who is the expert on this topic.

**Comment by albertoperdomo** [comment]
Internal note: We are prioritizing the green-field workflow for now.

**Comment by ianwensink** [comment]
@mavilein I guess `migrate up` does what you’re saying it does, but I think the problem lies with `migrate save`. Migrate save will compare the latest schema to the latest migration, and save the diff as a new migration, correct? When there are no migrations yet, this will result in an initial migration with create statements for every tabel, since “none existed yet”. This is untrue, though, in the case where I already have a production database with tables in it. The initial migration is only useful for empty databases, but in production it can be skipped.

**Comment by albertoperdomo** [comment]
@ianwensink Thanks for taking the time to report this.

We recently released Prisma Migrate in Preview. Here are the release notes (2.13.0): https://github.com/prisma/prisma/releases/tag/2.13.0

This evolution of Prisma Migrate has substantial changes compared to the experimental version for which you opened this issue. The workflow described here is also supported via something we're calling baselining workflow.

Prisma Migrate can register specific migrations as already executed so they are skipped in the future, thus allowing to write new migrations for existing databases. The process to baseline an existing database is documented here: https://www.prisma.io/docs/guides/prisma-guides/prisma-migrate-guides/add-prisma-migrate-to-a-project#baseline-your-production-environment

If you come acrossany other issues in the preview version, please feel free to open a [new issue in prisma/prisma](https://github.com/prisma/prisma/issues/new/choose).
For general feedback on Prisma Migrate Preview, feel free to chime in [on this issue](https://github.com/prisma/prisma/issues/4531).
