### ISSUE TITLE
Allow to set migration storage table name

### ISSUE THREAD

**Issue by wanxger** [prisma/migrate#495]
## Problem
Can't set migration storage table name.

## Suggested solution
Allow to set migration storage table name just like Sequelize.

## Alternatives
Add ```migrationStorageTableName``` key to ```datasource``` block in ```schema.prisma``` file.

## Additional context
[Sequelize Migration Storage](https://sequelize.org/v5/manual/migrations.html#migration-storage)

**Comment by albertoperdomo** [comment]
Hello @wanxger,

can you explain why you'd want to chan get the migration storage table name?

**Comment by wanxger** [comment]
Hello @albertoperdomo,
I'm using a MySQL database in cloud, table names only support lowercase letters.

**Comment by albertoperdomo** [comment]
Thanks for the follow-up comment @wanxger - I can see that can be an issue.
Are you currently blocked by this?

**Comment by wanxger** [comment]
I replace [_Migration](https://github.com/prisma/prisma-engines/blob/f3522ca0a764c269369a43cc609df7fe526155ed/migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs#L293) with _migration, and build.
