### ISSUE TITLE
Can not create SQLite database when using protocol `sqlite://`

### ISSUE THREAD

**Issue by janpio** [prisma/migrate#497]
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "sqlite://dev.db"
}

model User {
  id    String  @default(cuid()) @id
  email String  @unique
  name  String?
}
```

leads to endless spinner on `prisma migrate save --experimental`.

With `  url      = "file:./dev.db"` it creates the file, but does not finish the process and you have to use Ctrl+C (but that is tracked in another issue).

(Windows)

**Comment by jsplate** [comment]
I had the same problem on Windows. Slight difference: Even Ctrl+C did not stop the command from running. The db file was created, but no migrations. On Ubuntu 20-04 it runs fine.

**Comment by janpio** [comment]
What was actually https://github.com/prisma/migrate/issues/342 @jsplate - which should be fixed in the `@dev` version now and will be inlcuded in the next release on `latest` as well.

**Comment by Jolg42** [comment]
So `sqlite://` is actually expected to fail as it's not supported, changing it to `file:` should work.
