### ISSUE TITLE
`prisma2 lift fix` does not work

### ISSUE THREAD

**Issue by nickreynke** [prisma/migrate#51]
Similar to #37 the command `prisma2 lift fix` does not work either and also isn't really documented. It's just (wrongly) stated within the `lift.lock` file:

```lock
# IF THERE'S A GIT CONFLICT IN THIS FILE, DON'T SOLVE IT MANUALLY!
# INSTEAD EXECUTE `prisma lift fix`
# lift lockfile v1
# Read more about conflict resolution here: TODO
```

Results in:

```bash
➜  prisma2 lift fix

! Unknown command "fix"

🏋️‍‍‍  Migrate your database with confidence

Usage

  prisma2 lift [command] [options]

Options

  -h, --help   Display this help message

Commands

    save   Create a new migration
    docs   Open documentation in the browser
    down   Migrate your database down
      up   Migrate your database up

Examples

  Create new migration
  $ prisma2 lift save

  Migrate up to the latest datamodel
  $ prisma2 lift

  Preview the next migration without migrating
  $ prisma2 lift up --preview

  Rollback a migration
  $ prisma2 lift down 1

  Get more help on a lift up
  $ prisma2 lift up -h

```

**Comment by timsuchanek** [comment]
Thanks for reporting @nickreynke, we're aware that this has not yet been implemented.
Did you hit a particular merge conflict in the `lift.lock` file?
If so, we would like to help you solve it manually for now, as it'll still take 2-3 weeks until we have the `fix` command.

**Comment by nickreynke** [comment]
Thank you for your help @timsuchanek :) No, I've just seen that it's not yet implemented. Do not have a merge conflict :) Keep up the good work on Prisma2!

**Comment by alizhdanov** [comment]
Hi, any updates on this one?

**Comment by bstro** [comment]
Is fixing manually still the best option?

**Comment by Thieffen** [comment]
+1
https://github.com/redwoodjs/redwood/pull/307
