### ISSUE TITLE
The above error occurred in the <TabIndexProvider> component with migration, table already exists

### ISSUE THREAD

**Issue by Slmii** [prisma/migrate#525]
## Bug description
After running `migrate up` for a second time I get the following error message:
![image](https://user-images.githubusercontent.com/9927849/88219891-88ab2400-cc62-11ea-8ac0-4a5e1ea1ab15.png)

Running it the first time init worked fine with the following schema:
```
generator client {
  	provider = "prisma-client-js"
}

datasource db {
	provider = "mysql"
	url      = env("DATABASE_URL")
}

model User {
	id		      Int       @default(autoincrement()) @id
	uuid          String    @default(uuid())
	email         String    @unique
	first_name    String
	last_name     String
	password      String
	status        Boolean   @default(true)
	userGroup     UserGroup @relation(fields: [user_group_id], references: [id])
	user_group_id Int
	created_at    DateTime  @default(now())
	updated_at	  DateTime  @updatedAt
}

model UserGroup {
	id		    Int       @default(autoincrement()) @id
	uuid        String    @default(uuid())
	name  		String
	description String? 
	created_at  DateTime  @default(now())
	updated_at	DateTime  @updatedAt

	users 		User[]
}
```
Afterwards I added another model with its relation
```
model User {
        roles       Role[]
}
model Role {
	id		    Int       @default(autoincrement()) @id
	uuid        String    @default(uuid())
	name  		String
	description String? 
	created_at  DateTime  @default(now())
	updated_at	DateTime  @updatedAt

	users 	 	User[]
}
```
when running `migrate up` again it causes the error above in the image. With DEBUG I get the additional error:
![image](https://user-images.githubusercontent.com/9927849/88220454-47ffda80-cc63-11ea-80e1-234b793ac4e6.png)

## How to reproduce

1. initialize db with migrate
2. add a model with many-to-many relationship
3. run migrate up again

## Expected behavior
Create the (existing) tables, if not it means I cannot run migrate again after adjusting the schema

## Prisma information
See above in the description

## Environment & setup

- OS: Windows 10
- Database: Mysql
- Node.js 12.16.1
- Prisma version:
```
@prisma/cli          : 2.2.2
Current platform     : windows
Query Engine         : query-engine a9e8c3d97ef2a0cf59256e6b26097f2a80f0a6a4 (at C:\Users\selam\Desktop\graphql-nexus\node_modules\@prisma\cli\query-engine-windows.exe)
Migration Engine     : migration-engine-cli a9e8c3d97ef2a0cf59256e6b26097f2a80f0a6a4 (at C:\Users\selam\Desktop\graphql-nexus\node_modules\@prisma\cli\migration-engine-windows.exe)
Introspection Engine : introspection-core a9e8c3d97ef2a0cf59256e6b26097f2a80f0a6a4 (at C:\Users\selam\Desktop\graphql-nexus\node_modules\@prisma\cli\introspection-engine-windows.exe)
Format Binary        : prisma-fmt a9e8c3d97ef2a0cf59256e6b26097f2a80f0a6a4 (at C:\Users\selam\Desktop\graphql-nexus\node_modules\@prisma\cli\prisma-fmt-windows.exe)
```

```

**Comment by Slmii** [comment]
@tomhoule I did some more testing, I dropped all the tables in the database, after that I renamed all of the models in the prisma schema to snake_case, tried another migration and now it gives me an error about `Table _migration doesnt exist`. In the readme of the migration there's only a part of dropping the table `_migration` and not about creating one. Im not sure of case sensitivity is the issue here.

**Comment by Slmii** [comment]
so I added the `_migration` table manually to the database, did an migration with an updated schema (changes naming to snake_case). The updated were applied but it still gives the error `Table _migration doesnt exist`. 

Also, I did the same test with CamelCase in the prisma schema model names. I added the `_migration` table manually, but this time it gave me an error with `Table 'user' already exists'. So with CamelCase and snake_case I got both different errors.

**Comment by tomhoule** [comment]
This is a known issue around the default settings for MySQL on windows [doing something weird](https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html) with case conversions for identifiers, We want to find the time to investigate this soon. There is a [tracking issue](https://github.com/prisma/prisma-engines/issues/950).

We should however keep this issue open, because short term we have to fix the error handling. We should at least return a readable error here.

**Comment by Jolg42** [comment]
Closing this issue in favor of the tracking issue about <TabIndexProvider> component https://github.com/prisma/migrate/issues/521

**Comment by janpio** [comment]
What about the underlying error? See also @tomhoule 's last message here.

**Comment by Jolg42** [comment]
@janpio I closed the issue because @tomhoule said the tracking issue for the underlying error is https://github.com/prisma/prisma-engines/issues/950
