### ISSUE TITLE
Suggested Command is missing npx

### ISSUE THREAD

**Issue by do4gr** [prisma/migrate#529]
After running `npx prisma migrate save --name init --experimental` the output suggests the next command to run, but the suggestion is missing the npx and therefore fails: 

<img width="468" alt="Screen Shot 2020-07-23 at 11 59 11" src="https://user-images.githubusercontent.com/16278407/88274405-f2b3df80-ccdb-11ea-94a9-5117803ed097.png">

We should adjust all command suggestions so that they are immediately runnable when copy pasted.

Versions:
@prisma/cli          : 2.3.0
Current platform     : darwin
Query Engine         : query-engine e11114fa1ea826f9e7b4fa1ced34e78892fe8e0e (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli e11114fa1ea826f9e7b4fa1ced34e78892fe8e0e (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core e11114fa1ea826f9e7b4fa1ced34e78892fe8e0e (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt e11114fa1ea826f9e7b4fa1ced34e78892fe8e0e (at node_modules/@prisma/cli/prisma-fmt-darwin)

**Comment by Jolg42** [comment]
We could do that for all the CLI commands for npx indeed, that would be super nice.

**Comment by albertoperdomo** [comment]
We will create an issue to tackle this across the board, not only on migrate.

**Comment by Jolg42** [comment]
It just works now 😉 
<img width="547" alt="Screen Shot 2020-08-24 at 15 31 19" src="https://user-images.githubusercontent.com/1328733/91050416-e5fa1280-e61e-11ea-82e8-a05a1822079f.png">
