### ISSUE TITLE
Postgres Binary Type

### ISSUE THREAD

**Issue by rossinicolas** [prisma/migrate#538]
## Problem
Migration when my database has binary fields in some tables

## Suggested solution
My suggestion is if Prisma 2 do not support binary types in the introspection workflow, prisma migrate will be do not support this kind of field in the other ways....becouse i can't use all the power of this command when i create new mode, prisma migrate try to DROP the field and that's not correct.

**Comment by tomhoule** [comment]
We are working on supporting this. Closing this as duplicate, you can follow the progress on https://github.com/prisma/prisma/issues/4330
