### ISSUE TITLE
`up` output does not include all created tables

### ISSUE THREAD

**Issue by janpio** [prisma/migrate#555]
```
Database Changes:

Migration            Database actions             Status

20200816131459-init  5 CreateTable statements.    Done 🚀  
```

In reality it created 6 normal tables (1 for implicit relations) and the Migration table.

**Comment by tomhoule** [comment]
It's a point of detail, but the implicit relation table should be included in the `CreateTable`s, only the `_Migration` table is special.

**Comment by janpio** [comment]
I agree. The implicit tables are not represented by models, that probably where this confusion comes from. It might be useful to mention both models and tables in the success message for the full information to the user.

**Comment by tomhoule** [comment]
This is no longer relevant since we do not print that in migrate preview. Closing the issue. Thanks!
