### ISSUE TITLE
Lift: Migration readme should be adapted depending on the prisma config

### ISSUE THREAD

**Issue by steebchen** [prisma/migrate#563]
When saving a migration, a readme.md gets generated. It contains a "Photon Usage" section, which describes information on how to use a specific build for a given migration. However, since lift can be used by any project with any generator (or none), this information should probably be not added by default.

This extra information could be generated when the specified generator is `photonjs` as specified in the schema.prisma file. Maybe we could define how or where this additional information is stored (in the prisma2 CLI? In the generator manifest?).

<img width="587" alt="image" src="https://user-images.githubusercontent.com/5013932/67863807-e58b0b00-fb24-11e9-8b0e-89b24d7e0ddd.png">

**Comment by tomhoule** [comment]
Thanks @steebchen for the suggestion — we don't have READMEs for migrations anymore so that problem is gone :)
