### ISSUE TITLE
Add explicit migrations configuration to Prisma schema

### ISSUE THREAD

**Issue by schickling** [prisma/migrate#565]
Currently Lift works out of the box when using the Prisma CLI (and unselecting Lift in the init flow doesn't have any effect on the schema which results in users running `prisma2 dev` migrating their DB unintentionally).

We should add some kind of Lift configuration to the `schema.prisma` to (1) explicitly enable Lift and (2) provide optional configuration options such as the `migrations` directory etc.

**Comment by Jolg42** [comment]
Closing as old issue.
