### ISSUE TITLE
Migrate save fails when the name has a space with unexpected error message

### ISSUE THREAD

**Issue by divyenduz** [prisma/migrate#585]
## Bug description

If name's value has a space, CLI doesn't recognize the --experimental flag.

## How to reproduce

- `yarn prisma migrate save --name create user --create-db --experimental` (fails)

```
yarn run v1.22.4
$ /Users/divyendusingh/Documents/prisma/e2e-tests/platforms/vercel-with-redwood/node_modules/.bin/prisma migrate save --name create user --create-db --experimental
Error: Please provide the --experimental flag to use this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

- `yarn prisma migrate save --name "create user" --create-db --experimental` (works)

## Expected behavior

Migrate CLI should work when the name has spaces but is not quoted

## Prisma information (bundled with redwood 0.17.2)

```
divyendusingh [vercel-with-redwood]$ yarn prisma --version                                                                                    1 ↵
yarn run v1.22.4
$ /Users/divyendusingh/Documents/prisma/e2e-tests/platforms/vercel-with-redwood/node_modules/.bin/prisma --version
@prisma/cli          : 2.6.1
Current platform     : darwin
Query Engine         : query-engine 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.272.0
✨  Done in 3.80s.
```

**Comment by albertoperdomo** [comment]
In order to supply whitespace in the --name argument, you need to use quotes, e.g. `--name "user table"` or `--name user \table`. Else, this will be picked up as separate CLI args.

In the Preview version of Prisma Migrate, supplying multiple words separated by whitespace without using the methods suggested above results in only the first word being applied as migration name.
