### ISSUE TITLE
Lift: introduce a delete/reset command

### ISSUE THREAD

**Issue by steebchen** [prisma/migrate#590]
Developers often have to run a full database cleanup for development or testing purposes. This is why it would be useful if lift would come with a `delete` CLI command, which drops the database: `prisma2 lift delete`.

Similar from the Prisma 1 behavior, this command could warn if there is existing data which would be deleted, but this again could be overridden by a --force flag: `prisma2 lift delete --force`. Maybe this command needs extra warnings or flags/checks to be extra cautious to prevent accidental usage.

An alternative name could be `reset` to communicate a full database reset instead of just deleting data, or both commands could be introduced to provide both behaviors.

**Comment by tomhoule** [comment]
Closing this, as we have `prisma migrate reset` now. Thanks!
