### ISSUE TITLE
Cannot use a Digital Ocean Managed DB due to sql_require_primary_key

### ISSUE THREAD

**Issue by jruiseco** [prisma/migrate#596]
Prisma migration files fail the following.

```
Oops, an unexpected error occured!
Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Server error: `ERROR HY000 (3750): Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.'
   0: migration_core::api::ApplyMigration
           with migration_id="20200804111054-initial_provision"
             at migration-engine\core\src\api.rs:79)
```

Has anyone been able to succesfully apply migrations to DigitalOcean managed DBS?

DB: Default Managed Digital Ocean Mysql 8 DB
Prisma Version: 2.5.1

Thoughts:

It appears that the Digital Oean managed DBS are expecting a primary key during table creation, but Prisma does not appear to set one. I am trying to modify the Digital Ocean setting to disable this check.

Further info:
https://www.digitalocean.com/docs/databases/mysql/

"Known issues: MySQL databases containing tables without a primary key and which contain more than 5000 rows may experience replication issues. To prevent this, DigitalOcean now requires you to add a primary key for each new table you create in any managed MySQL database created after 8 April 2020. We strongly recommend that you also add primary keys in existing databases to avoid replication issues."

It seems like we cannot use Digital Ocean for any of the relational tables in v 2.5.1 of Prisma.

**Comment by albertoperdomo** [comment]
Hello @jruiseco,

the join tables created for m-n relations using implicit syntax in Prisma Schema do not have primary keys in them. This seems to be the issue you are running into.

A workaround until we have a better solution would be to use to define a join model in which you can of course have a primary key.

Can you please confirm if this workaround works for you?

**Comment by jruiseco** [comment]
@albertoperdomo 

My current workaround was to switch to a different provider that allowed the primary key constraint to be disabled. 

Could you provide an example on how this join model would be done using the prisma migrations schema syntax?

**Comment by albertoperdomo** [comment]
```
model Post {
  id         Int                 @id @default(autoincrement())
  title      String
  categories CategoriesOnPosts[]
}
model Category {
  id    Int                 @id @default(autoincrement())
  name  String
  posts CategoriesOnPosts[]
}
model CategoriesOnPosts {
  post        Post     @relation(fields: [postId], references: [id])
  postId      Int       // relation scalar field (used in the `@relation` attribute above)
  category    Category @relation(fields: [categoryId], references: [id])
  categoryId  Int      // relation scalar field (used in the `@relation` attribute above)
  createdAt   DateTime @default(now())
  @@id([postId, categoryId])
}
```

You would add the primary column to the join model, in this case CategoriesOnPosts.
I've pasted the code from our [m-n relations reference docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/relations#many-to-many-relations).

**Comment by jruiseco** [comment]
Hello @albertoperdomo 

I see now the difference between implicit and explicit relations.

I am probably not going to change, and hope that a future improvement to implicit relations fixes this. Or I will simply continue using my custom database.

In either case, this does look like a good solution for those starting a new project from scratch.

**Comment by albertoperdomo** [comment]
Note to self to make sure this limitation is documented.

**Comment by albertoperdomo** [comment]
Created a ticket to make sure this limitation and the workaround is documented. https://github.com/prisma/docs/issues/958
