### ISSUE TITLE
Data Migrations

### ISSUE THREAD

**Issue by paniavula** [prisma/migrate#597]
### Computational Data
For some of the schema changes, data migrations would be required. For example, addition of a new column "Name" to "User" table could be a calculation value of "First Name" + "Last Name". In some cases, the new column value could be a complex computational value from other tables in the database
### Reference Data
As part of a release, we could require addition/removal of new records to the reference or enumerations data. For example adding new account_type to AccountType table.

In prisma migrate how can these DML specific migrations be done?

**Comment by erawk** [comment]
There's discussion of this over at #492, consider consolidating feedback there.

**Comment by tomhoule** [comment]
As of 2.13.0, the new migrate with imperative migrations (as SQL, currently) in in preview. Feedback is very much wanted :)

**Comment by albertoperdomo** [comment]
@paniavula Data migrations are currently supported via SQL in Prisma Migrate Preview.
Let's use https://github.com/prisma/prisma/issues/4688 to track the feature request for a Typescript DSL.
