### ISSUE TITLE
Multiple identical migration records in the _migration table

### ISSUE THREAD

**Issue by farminf** [prisma/migrate#598]
## Bug description

We use Prisma in our Nestjs application and the procedure that we have for starting up is that every time we start the application we run migrations by `prisma migrate up --experimental` before starting the application itself.
In our production, we use AWS ECS for running our application and there we have multiple containers running. we got an error in there that:

we have only one migration in our migration file and on the DB when I check _migration table, there are 2 identic records!
the only reason that I think is that we run up multiple containers at the same time, and they want to do the migration at the same time, so we get 2 records on the DB for the same migration and then the next deployment will fail because it gets out of sync...

anyone have the same experience or have any idea about this? how can we fix this?

## How to reproduce

I think by running a migration from multiple processes at the same time it will happen again.

## Expected behavior

It should not create another record for the same migration

## Prisma information

- "@prisma/client": "2.4.1"
- "@prisma/cli": "2.4.1",

## Environment & setup

- OS:  AWS ECS containers (linux)
- Database:  Postgres
- Node.js version:  12
- Prisma version:

- "@prisma/client": "2.4.1"
- "@prisma/cli": "2.4.1",

```

```

**Comment by tomhoule** [comment]
This is something that needs to be dealt with in the prisma migration engine. It's a known issue, and there is a clear action plan in https://github.com/prisma/prisma-engines/issues/1118. We will deal with this before we consider migrate not experimental anymore.

**Comment by farminf** [comment]
Thanks @tomhoule for the reply... and do you have any idea when migrate will be production-ready approx?

**Comment by tomhoule** [comment]
We don't have a public timeline yet, but I can say that several of us have been working on making migrate shippable in the last few months. There is work happening at the moment and it's a priority.

**Comment by farminf** [comment]
Thanks a lot... we're looking forward to it :)
