### ISSUE TITLE
Allow "Squashing" Migrations

### ISSUE THREAD

**Issue by nahtnam** [prisma/migrate#599]
## Problem
Whenever I'm working on a PR in my project, I first create a migration to make the changes I want. Half way through I realize that I made a mistake in the migration and want to make a field optional, etc. Repeat that a few times. Now if I open a PR, there are 15 files changes for the 5 migrations that I made. It would be nice if I could "squash" all 5 of those into one

## Suggested solution
A command such a `npx prisma migrate squash --last 5`

## Alternatives
You could:

1. Delete all 5 migrations
2. Drop your db, migrate up to the latest committed changes
3. Then create a new migration

But thats super annoying because it wipes your data in your local db

## Additional context
N/A

**Comment by asciant** [comment]
Glad I'm not the only one, this would be a great feature.

**Comment by jthn** [comment]
Thinking through this same thing. Would it be possible to delete the migrations, remove the entries from your local migration table and run:

```
$ prisma migrate dev --create-only --preview-feature
```

...and then check that in?

There'd obviously be problems if you're collaborating and someone else had run some of those transitional migrations.

**Comment by albertoperdomo** [comment]
@nahtnam With Prisma Migrate Experimental ([released in 2.13.0](https://github.com/prisma/prisma/releases/tag/2.13.0)), this is now better supported.

The workflow as described by @jthn should work, as long as these migrations have not been merged yet:

1. Remove migrations you want to get rid of
2. Create new migration with `prisma migrate dev`
3. Commit the new migrations

In development, anyone who had previously executed these migrations that are now missing, will go through a reset of the development database the next time they run `prisma migrate dev`. This will be at least the person "squashing" the migrations.

You should not do this if these migrations have already been applied in any non-development environment you don't feel comfortable resetting, i.e. staging or production.

Alternative method: use `prisma db push` up to the point you feel confident about the DB schema, then use `prisma migrate dev` to create the actual migration for the PR.

We would encourage you to try out Prisma Migrate Preview. If you come across this or any other issue in the preview version, please feel free to open a [new issue in prisma/prisma](https://github.com/prisma/prisma/issues/new/choose).
For general feedback on Prisma Migrate Preview, feel free to chime in [on this issue](https://github.com/prisma/prisma/issues/4531).
