### ISSUE TITLE
Mirroring Hasura in Auto Migration

### ISSUE THREAD

**Issue by Maxvien** [prisma/migrate#611]
I think Hasura Migration is great. However we must run its `graphql-engine` to use the migration tool while all we need is just an ORM. 

Regarding to Prisma Migration, I think you guys should learn from it.

https://hasura.io/docs/1.0/graphql/core/migrations/index.html

**Comment by tomhoule** [comment]
We did take this tool into account in the research phase that lead to the preview release of prisma migrate in 2.13.0. Thanks for the resource, and please open more feedback/suggestion issues, we are always glad to read these :)
