### ISSUE TITLE
report

### ISSUE THREAD

**Issue by baatten** [prisma/migrate#622]
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v12.18.3           | 
| Prisma CLI  | 2.10.0             | 
| Binary      | af1ae11a423edfb5d24092a85be11fa77c5e499c| 

## Error
```
Error: Error in migration engine.
Reason: [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:91:66] called `Result::unwrap()` on an `Err` value: ConnectionError { quaint_error: Error { kind: Timeout("SQLite database is busy"), original_code: Some("5"), original_message: Some("database is locked") }, connection_info: Sqlite { file_path: "dev.db", db_name: "quaint" } }

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

```

**Comment by tomhoule** [comment]
I think we do have a proper error for this now. Please open a new issue if it crashes again. Thanks!
