### ISSUE TITLE
Running 'prisma migrate up' does not work when the _Migrations table has records while `prisma/migrations` is empty

### ISSUE THREAD

**Issue by beeman** [prisma/migrate#624]
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v14.13.1           | 
| Prisma CLI  | 2.10.0             | 
| Binary      | af1ae11a423edfb5d24092a85be11fa77c5e499c| 

## Error
```
Error: Error in migration engine.
Reason: [libs/sql-schema-describer/src/walkers.rs:214:27] index out of bounds: the len is 0 but the index is 0

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

```

I got the error above when I had no local migrations (I was able to get rid of them thanks to 'prisma db push' in Prisma 2.10), but the `_Migrations` table in the DB still existed.

It might be a more common use case where folks decide to get rid of their migration, but forget to clear the `_Migrations` table, so maybe it's something you could check for.					

Happy to provide any additional details if needed.

**Comment by tomhoule** [comment]
Hi Bram! This can't happen with `db push`, so it should be fine now :)
