### ISSUE TITLE
crashed after the first migration

### ISSUE THREAD

**Issue by tedoham** [prisma/migrate#625]
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v14.14.0           | 
| Prisma CLI  | 2.10.0             | 
| Binary      | af1ae11a423edfb5d24092a85be11fa77c5e499c| 

## Error
```
Error: Error in migration engine.
Reason: [libs/sql-schema-describer/src/walkers.rs:214:27] index out of bounds: the len is 0 but the index is 0

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

```

**Comment by tomhoule** [comment]
This is a known issue, we're working on fixing this. Thanks for reporting.

**Comment by tomhoule** [comment]
Would you be able to share your schema and/or your migrations?

**Comment by tomhoule** [comment]
We worked on this problem and just released a fix in 2.10.1. Can you confirm that this does not happen anymore with the new version?

**Comment by tomhoule** [comment]
Other users confirmed the problem is gone for them in 2.10.1, so I'll close this as duplicate.

**Comment by smakosh** [comment]
I'm having the same issue @tomhoule

**Comment by tomhoule** [comment]
Please open an issue with more details and we can look into it, it will be forgotten if it stays in the comments of a closed issue.

**Comment by smakosh** [comment]
The issue happened because I wasn't using `npx prisma migrate...`, that worked fine.
