### ISSUE TITLE
Couldn't parse default value

### ISSUE THREAD

**Issue by timmaybrown** [prisma/migrate#643]
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v12.18.2           | 
| Prisma CLI  | 2.11.0             | 
| Binary      | 58369335532e47bdcec77a2f1e7c1fb83a463918| 

## Error
```
Error: [libs/sql-schema-describer/src/mssql.rs:251:30] Couldn't parse default value
```

**Comment by tomhoule** [comment]
Support for microsoft SQL server in migrate is not implemented, it should not be possible to start it with that provider. Can you share your `datasource` and `generator` blocks from your prisma schema, so we can reproduce this and make sure feature gating is properly implemented?

**Comment by tomhoule** [comment]
MSSQL support in migrate is now in preview — you shouln't be experiencing this error anymore with 2.13.0. Please open a new issue if you find problems on a more recent version. Thanks!
