### ISSUE TITLE
blitz db migrate

### ISSUE THREAD

**Issue by coman-rpx** [prisma/migrate#644]
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v12.19.0           | 
| Prisma CLI  | 2.10.2             | 
| Binary      | 7d0087eadc7265e12d4b8d8c3516b02c4c965111| 

## Error
```
Error: [libs/sql-schema-describer/src/postgres.rs:125:44] could not get columns
```

**Comment by tomhoule** [comment]
Hi! Thanks for the report, can you give us more information about your postgres installation? (version, cloud provider if applicable, etc.)

**Comment by tomhoule** [comment]
This should be fixed (it should not error anymore). If you experience issues with a newer version of migrate, please open a new issue. Thanks :)
