### ISSUE TITLE
Oops, an unexpected error occured! table columns not found

### ISSUE THREAD

**Issue by kyuwoo-choi** [prisma/migrate#647]
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v14.8.0            | 
| Prisma CLI  | 2.11.0             | 
| Binary      | 58369335532e47bdcec77a2f1e7c1fb83a463918| 

## Error
```
Error: [libs/sql-schema-describer/src/mysql.rs:156:53] table columns not found
```

## Desc
ran `npx prisma introspect` results. And sure, a table exists in the db.
```
Introspecting based on datasource defined in prisma/schema.prisma …
Oops, an unexpected error occured!
[libs/sql-schema-describer/src/mysql.rs:156:53] table columns not found

Please help us improve Prisma by submitting an error report.
Error reports never contain personal or other sensitive information.
Learn more: https://pris.ly/d/telemetry
```

**Comment by kyuwoo-choi** [comment]
It was because of insufficient privileges.
closing it.

**Comment by do4gr** [comment]
Hey, thanks for reporting this. 

Could you please describe the permission setup when you were experiencing that? It seems like the user was able to see the table but not it's columns? 

Any more insight would be interesting to us.
