### ISSUE TITLE
On Trying to.migrate with   native:  Some of the requested preview features are not yet allowed in migration engine

### ISSUE THREAD

**Issue by wortforfilms** [prisma/migrate#661]
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v15.3.0            | 
| Prisma CLI  | 2.10.2             | 
| Binary      | 7d0087eadc7265e12d4b8d8c3516b02c4c965111| 

## Error
```
Error: Error in migration engine: Dec 04 18:23:54.585  INFO migration_engine: Starting migration engine RPC server git_hash="7d0087eadc7265e12d4b8d8c3516b02c4c965111"
```

**Comment by Jolg42** [comment]
Hi @wortforfilms

Did you get a bug with native types maybe?

Note: Prisma Migrate doesn't support the native types feature yet.

**Comment by wortforfilms** [comment]
No I am trying to see if byte streaming is possible with prisma. It was
recommended on stackflow so I tried configuring prisma with native support.
I am trying to save bytes from web frontend.

**Comment by tomhoule** [comment]
@wortforfilms it's not very intuitive, but bytes are part of the `nativeTypes` preview feature, which isn't available in combination with migrate yet. We are working on it though, it's a temporary limitation. Thanks for reporting.

**Comment by Jolg42** [comment]
Closing as it's working as expected.
